### ISSUE TITLE
Interactive table UX/UI requests

### ISSUE THREAD

**Issue by libby-maier** [hubmapconsortium/hra-ui#258]
# Interactive table UX/UI requests

## UX functionality missing from Dev Notes
Per the [interactive table functionality note](https://github.com/hubmapconsortium/hra-ui/wiki/Functional-Tissue-Unit-Explorer---Design-Notes-for-Development#interactive-table-functionality), users need to be able to copy text from the information hovercard. Ideally, they may click on links as well. Links should always open in a new tab.

If hovering over the card is not easy to build, I recommend allowing users to click the percentage of cells in FTU target to keep the information card in an expanded state. They may click the target again to close it.

Please contact me with questions!

## UI
1. The expand icon should match [the Figma file](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Atlas-Design-System?type=design&node-id=326-2684&mode=design&t=SQK0P0z6OCCJqEtj-4).
2. Borders were specified for cell count and associated biomarkers on the table.
3. Is it possible to reduce the font size of the legend titles slightly to get the Biomarker Expression Mean in FTU title on one line? This might involve sitting together and iterating to resolve. Just ping me!
4. The font on the legend's informational hover cards should match [the Figma file](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-Explorer?type=design&node-id=509-36553&mode=design&t=dk2cB2Vmf9pNwK7m-4).
5. The font on the biomarker buttons should match [the Figma file](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-Explorer?type=design&node-id=337-21839&mode=design&t=dk2cB2Vmf9pNwK7m-4). The kerning (space between the letters) and the weight appear different than the font specified.
6. The selected state and hover states of the biomarker buttons on the interactive table should match [the Figma file](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-Explorer?type=design&node-id=337-21839&mode=design&t=dk2cB2Vmf9pNwK7m-4). Currently, the text color of the selected state does not match the spec. Additionally, the hover functionality is showing a light red, instead of the gray specified. Lastly, the selected color bar indicator appears to be a different color than the crimson specified. The height of this visual indicator may need to be increased to match the Figma specification.
![7CCD22EE-0CB1-40BA-BE82-EFAFF4786E96](https://github.com/hubmapconsortium/hra-ui/assets/97060856/74597732-ee1c-4f2b-8550-7b7bc28e6591)

# Build:
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/885dcf13-0959-43a0-88fa-19c60f305575)
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/c7d603ff-10d6-4358-8aba-71f27f7cddc5)

# Figma
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/28aad276-7b40-4652-b4b4-217ab3c66c5a)
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/7ce54b41-0614-4773-962f-744259e1e7d2)

**Comment by libby-maier** [comment]
The legend text and icon for Biomarker Expression Mean in FTU is still an issue. The specification was designed for 1920x1080 breakpoints. The font size has been reduced but it still wraps. Why is the icon pushing the legend title text to wrap around? Please make sure the tooltip text and icon display on the same line.

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/08f82648-d7c6-454a-974f-c7efd57ca07d)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/df223117-809d-4353-a26b-612f088fc3c8)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/f34c8a06-bfb9-43c9-9063-eea45fe51759)

## Autolayout details for this frame in Figma:
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/fbd8ea43-6ac1-49ef-ad8e-97555045f70c)

**Comment by edlu77** [comment]
Legend issue duplicated by #283
