### ISSUE TITLE
Design Issues Fix

### ISSUE THREAD

**Issue by jsaikiran19** [hubmapconsortium/hra-ui#259]
Fixes Issues raised by Libby:

#253 :

- [x] The FTU library should be fixed to its position on the landing page. When a user scrolls, the FTU library should scroll with the page content. If the user hovers over the FTU library and scrolls, the library listings move.
- [x] The header for the FTU library is not fixed. Please fix this to the top of the FTU library component to match the spec, if possible. 
- [x] Match the scrollbar style in the FTU viewing component to keep scrollbar styles consistent. 

#254 :

- [x] The landing page's main Explore FTUs call to action button ideally matches the specification. If the moving arrow functionality for this button is not possible, please update the font/colors/state to match the specifications. The icon also does not match the specification, so if that could be updated to the icon as specified, that would be great! 
- [x] The rest of the buttons around the interface need to match the specifications precisely, if possible. The kerning (the space between the letters), the font size, and the weight of the font look different in comparison to Figma.
- [x] The About button needs more space between the underline and the text.
- [x] The Collaborate with the HRA Team button needs to all be on one line, if possible.
- [x] The Download button icon does not match the specification. If the icon could be updated to the specified icon, that would be great! 

#257 :

- [x] Highlight functionality on the interactive table while hovering over an area of an FTU --Sai --Done

#258 --Raj:

- [x] The expand icon should match [the Figma file](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Atlas-Design-System?type=design&node-id=326-2684&mode=design&t=SQK0P0z6OCCJqEtj-4).
- [x] Borders were specified for cell count and associated biomarkers on the table.
- [x] Is it possible to reduce the font size of the legend titles slightly to get the Biomarker Expression Mean in FTU title on one line? This might involve sitting together and iterating to resolve. Just ping me!
- [x] The font on the legend's informational hover cards should match [the Figma file](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-Explorer?type=design&node-id=509-36553&mode=design&t=dk2cB2Vmf9pNwK7m-4).
- [x] The font on the biomarker buttons should match [the Figma file](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-Explorer?type=design&node-id=337-21839&mode=design&t=dk2cB2Vmf9pNwK7m-4). The kerning (space between the letters) and the weight appear different than the font specified.
- [x] The selected state and hover states of the biomarker buttons on the interactive table should match [the Figma file](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-Explorer?type=design&node-id=337-21839&mode=design&t=dk2cB2Vmf9pNwK7m-4). Currently, the text color of the selected state does not match the spec. Additionally, the hover functionality is showing a light red, instead of the gray specified. Lastly, the selected color bar indicator appears to be a different color than the crimson specified. The height of this visual indicator may need to be increased to match the Figma specification.

**Comment by libby-maier** [comment]
Relevant table lines do not currently highlight on hover of the renal corpuscle.

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/ad9fcf07-fb23-4353-9242-6e231a3737ce)

**Comment by edlu77** [comment]
> Relevant table lines do not currently highlight on hover of the renal corpuscle.
> 
> ![image](https://user-images.githubusercontent.com/97060856/275902904-ad9fcf07-fb23-4353-9242-6e231a3737ce.png)

Waiting on data for renal corpuscle
