### ISSUE TITLE
Fullscreen toggle button needs to feel more like a button

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/hra-ui#278]
@libby-maier please weigh in on your expectations for this, but I feel like there needs to be more button-like behavior on the full screen toggle. This includes a cursor change on hover, ripple effects like other buttons, outline on hover, ... essentially it should look and feel like a flat button.

**Comment by libby-maier** [comment]
Hi @bherr2, states were specified for this button in the [old design system file](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Atlas-Design-System?type=design&node-id=318-3347&mode=design&t=BJpbJHxDIUWhHRoj-4):

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/b91961d8-845a-4f11-ad40-4f77062451a2)

A hover state is specified in the interactive prototype:
![6201E7B7-97A3-4B07-A1F1-098DB5D33FB2](https://github.com/hubmapconsortium/hra-ui/assets/97060856/07f93976-62de-4f0f-9be1-fa05863ad4ab)

Getting it closer to the spec would be appreciated!

**Comment by bherr2** [comment]
Ok, thanks! That's good enough for us to go on for fixing this.
