### ISSUE TITLE
Guidance on increasing the size of the sources list

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/hra-ui#279]
@libby-maier need some input here. The sources list (ie the bottom right list of datasets) is extremely small (on my screen I usually can only see on source at a time). Not sure what is the best approach here, but the right-hand part of the screen feels like it needs some reworking a bit (especially on sizing). If there is a quick fix for MVP1 I'd like to explore it. MVP2 might need to revise this more drastically (like putting data sources as another tab instead of at the bottom)

**Comment by libby-maier** [comment]
@bherr2, please review the three possibilities designed today:

## Option 1
- Two rows of buttons for the interactive table in the same style we have currently.
- [View Figma node](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-Explorer?type=design&node-id=4727-57215&mode=design&t=xhjKdrBU0N2G0kB4-4)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/a26b2fa3-8d65-4633-8726-a24ba668992f)


## Option 2
- Decrease the font size and make the interactive table buttons closer to [M3 tabs](https://m3.material.io/components/tabs/overview).
- [View Figma node](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-Explorer?type=design&node-id=4730-62702&mode=design&t=xhjKdrBU0N2G0kB4-4)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/a1ec756d-2a38-414e-972c-c4c60f5bb907)


## Option 3
- A button on the footer navigation that opens a modal.
- [View Figma node](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-Explorer?type=design&node-id=4731-65879&mode=design&t=xhjKdrBU0N2G0kB4-4)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/19ec418f-6b70-4de5-b8e9-49919607b636)
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/eb50387b-8e39-4dfa-8b96-24dbfc294d82)

**Comment by libby-maier** [comment]
@bherr2 I edited the above comment and added a preferred option. Please let me know if more is needed on this. Thank you!

**Comment by bherr2** [comment]
Ok, thank you!

**Comment by libby-maier** [comment]
The proportions of the right side menus need to be addressed but the font has been resized.
