### ISSUE TITLE
Update landing page welcome section with specified illustration

### ISSUE THREAD

**Issue by libby-maier** [hubmapconsortium/hra-ui#292]
# Update landing page welcome section with specified illustration

- [x] Replace the current landing page's welcome section illustration with the [specified illustration](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-Explorer?type=design&node-id=4699-53084&mode=design&t=NKICcbwylQUaqAmx-4). Ensure it resizes responsively when adjusting in browsers.

## Figma
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/ca0dce16-399d-4240-ac54-2c9a4d56bafe)

## FTU Explorer as of 10.18.2023
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/f5e5f2fd-3b92-46bb-ad7c-6d9cf83e4515)

**Comment by edlu77** [comment]
Different illustration chosen, added in #295
