### ISSUE TITLE
wrap text for web component

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#312]
Hey team, I didn't realize how big this web component would be in production. Initially, I designed it to fit within a small fixed width, which is why I had each sentence of text spaced out. Can we iterate further and see how this web component looks with wrapped text?

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/1806bdd5-8b08-4875-8dfd-32264759e180)

## Figma

I mocked up a few changes in Figma here:
- Figma design file: [Web component title card](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-Explorer?type=design&node-id=595-51462&mode=design&t=MTYgNCdn24iWQzaG-4)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/175802cb-6895-47db-8105-de3eeae41c1f)

**Comment by bherr2** [comment]
It is supposed to fit into smaller pages. I think what we have on production doesn't demonstrate well how this should actually be used in a webpage.

**Comment by libby-maier** [comment]
Sounds good, I'll close this out. Thank you, @bherr2!

**Comment by libby-maier** [comment]
@bherr2 - I thought about this a little further, can we try this? I suspect it would look more cohesive to have two short sentences together in the container wrapping around, instead of spacing out each sentence like I specified initially.
