### ISSUE TITLE
web component - small adjustments for the FTU illustration/biomarker viewer

### ISSUE THREAD

**Issue by libby-maier** [hubmapconsortium/hra-ui#313]
Currently, on Google Chrome, I see a few small issues with the web component.
- There is a tiny line between the FTU library component and the FTU illustration viewer.
- The FTU illustration title is not showing currently on Google Chrome.
- The biomarkers tabs are missing. Is this because we don't have data or is this a bug?

## Production:
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/e1813afb-ec0e-419b-9ac4-064010fa40d3)

## [Figma](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-Explorer?type=design&node-id=587-48568&mode=design&t=MTYgNCdn24iWQzaG-4):
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/692443b3-7d43-4129-94a0-e47db63c5bfb)

**Comment by edlu77** [comment]
Fixed in production
