### ISSUE TITLE
FTU Explorer: Matrix & source data components

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#328]
# Right side interface: Table & source data UX/UI modifications
The ride side of the interface has received a significant redesign. Side by side is the current implementation versus the new approved design specification:

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/7623cd9b-4464-4513-b6f9-4f841f489aca)

## **Stakeholder Requirements**
- The table must always show 10 rows of cells and 10 biomarkers.
- The source data area must always show 4 rows of source data.
Please contact me if this is not possible. Ideally, we aim for something close to this, if these requirements can't happen.

### FTU Explorer
- Figma Design File: [Right side interface](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?type=design&node-id=5173-82090&mode=design&t=HNOvbJ17oW9jyVVk-4)
- [Figma Prototype Presentation](https://www.figma.com/proto/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?page-id=5058%3A64857&type=design&node-id=5173-81992&viewport=-26029%2C666%2C1.13&t=1oECOUe4JUuO8p6b-1&scaling=scale-down&starting-point-node-id=5173%3A81992&mode=design)
### HRA Design System
- [Component Library](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=0-1&mode=design)
- [Style Guide](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=103-4&mode=design)

### Source Data Modifications
- The source data area has been redesigned to include selection functionality.
  - The new table header can select all with the select all checkbox. Users may also sort ascending/descending by each column by clicking on the column header.
  - Selection of a row shows the available cell types by biomarkers for that specific dataset.
  - Deselecting a row reduces the available cell types by biomarkers to only selected datasets
  - By default, the table is sorted ascending by author's last name.
  - Data for the table is being sourced by Supriya Bindata at [Google Sheet: FTU Cell Count Table](https://docs.google.com/spreadsheets/d/1EvHMEc6a9_Dtmpr1D9uvAjl9LLOSvzfoP5Es-2zfF3E/edit#gid=1478902730). Direct all Source Data related questions to Supriya, please!
- There is no longer a footer at the bottom of the source data area. Buttons have been shifted to the header or to the FTU illustration component.
- Major UI aesthetic updates, including:
  - New fonts, color styles, padding, spacing, icons, buttons/button states.

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/4beeaab6-cfb7-46cd-933c-2d3f83ba26cb)
  
### Cell Types by Biomarkers Table Updates
- The former Cell Types by Biomarkers header has been removed to condense the information.
- Clicking on a cell now opens an overlay per issue #297 
- The biomarkers are now listed at a 45-degree angle.
- Design system scrollbars have been added.
- The biomarker listings are reduced when users deselect rows of data in the Source Data area.
- Major UI aesthetic updates, including:
  - New fonts, color styles, padding, spacing, icons, buttons/button states.

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/a8e8fdf5-d8d0-4da8-a29e-d843262f55f2)

**Comment by libby-maier** [comment]
@edlu77 heads up - I was using the wrong component in the design system for the scrollbars in the FTU Explorer design file. I have updated all scrollbars in the FTU explorer file to with the small scrollbar component!

### FTU Design File
- [Matrix + source data component with smaller scrollbars](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?type=design&node-id=5173-82090&mode=design&t=JWPN9WDhEUpQDbXi-4)

### Design System
- [Scrollbar atoms](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=2328-4185&mode=design&t=3li4hINwOkn2Ibc4-4)
- [Scrollbar component](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=2328-4293&mode=design&t=3li4hINwOkn2Ibc4-4)

**Comment by libby-maier** [comment]
# Design Review 3.27.2024
Thanks for meeting with me earlier @edlu77! Please ping me or come by my desk with any questions. I work remotely on Thursdays, so I'll be a Slack message away tomorrow! I am also happy to jump on a quick Zoom if needed!

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/2c599787-ef6b-4a4a-acaf-c8096d9e8cd2)

## Feedback & Questions
### Matrix Table
- The color of the header for the matrix table and the font colors have been updated. Can this be closer to the spec?
- Stakeholder requirement (see [above](https://github.com/hubmapconsortium/hra-ui/issues/328#issue-2137525141)): The table must always show 10 rows of cells and 10 biomarkers.
  - The columns appear to hug the biomarker names and have different widths in the build preview. The columns need to be the fixed width as specified to show as many columns as possible (ideally 10 per Katy). We will truncate longer biomarker names with 3 dots. On hover of the truncated biomarker label, the full biomarker names appear in a hover card. Biomarkers without truncation do not need hover cards.
  - Currently, the hover cards display the biomarker name in Times New Roman font. This will be updated to Inter if using the old design system or Metropolis if using the new design system. See [new hover card example](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?type=design&node-id=5213-100289&mode=design&t=4QBOnMyNaUmzJZT7-4) in Figma.
  - Is it possible to have this same functionality for truncated cell type names?
- The information icon seems a little cut off on my display.

### Source Data Table
- Is it possible for the source data header and the table header to have the same colors and heights as specified? It may look off to me because the table header is supposed to be gray. It appears slightly smaller in the current build preview too.
- Can we please use the [table sort button component](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=2015-4422&mode=design&t=qXvZtd2zjbXUIzqS-4), as specified in the design system, for all table sort buttons? The colors are currently off for the arrows/states.

## Nice to Have's (if possible/in scope per @bherr2 )
- It would be excellent to use the specified fonts.
- In the Matrix Table, scrollbars extend past the column and row headers. It would be nice to have this closer to spec, but it is not required unless Katy needs it.

**Comment by bherr2** [comment]
We don't have time to switch to the new design system. That is out of scope until next cycle. @libby-maier what is the expectation for the small web component? Specifically, how does the ability to select datasets effect it?

**Comment by libby-maier** [comment]
Hey @bherr2,

See the [source data mockup for the MVP2 web component](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?type=design&node-id=5524-77312&mode=design&t=6vYy0NJhgM0qMP5J-4) for visual guidance with the old design system.

I would expect the same functionality in the small web component like the web app. When users select/deselect certain datasets, their results are refined. Does this sound okay or did you want to go a different direction?

**Comment by bherr2** [comment]
Sounds good

**Comment by edlu77** [comment]
@libby-maier I made a few improvements to both the web components. Things should look a lot closer to the spec now. The table sort icon was a bit complicated to change so I had to leave that one alone for now, but it's the correct color at least.

Have a good weekend!

[Build preview](https://6607568954c2bc7a90598e85--hra-ui.netlify.app/apps/ftu-ui/#/)

[Build preview (small wc)](https://6607568954c2bc7a90598e85--hra-ui.netlify.app/apps/ftu-ui-small-wc/)

**Comment by LibbyUX** [comment]
@edlu77, thank you so much for implementing these changes!

## Small wc review
Overall, it looks great. I have 2 aesthetic suggestions, but we are there functionally.
- Is it possible to make the tab buttons fill the entire row? There is an awkward space at the end and it would be great to eliminate that. Please let me know if you need more from me to make this happen. Here's what I see on my 1920x1080 Google Chrome browser with 100% zoom:
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/00d61e39-adda-46b0-aa6d-f488530063ca)
- The arrows in the source data area appear a bit chunky. Is it possible to reduce their weight or use the arrows as specified?
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/b2adaa62-9d6c-434f-b9e1-88662b3ff0cd)

## main build preview review
I can't access the bottom toolbar footer or the source data area on my 1920x1080 Google Chrome browser with 100% zoom:
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/0ce5965f-750b-470a-bc5e-d5e3e455e042)
- We may have to iterate further on this so that it's available for standard laptop sizes. Let me know what I can do to help.

**Comment by edlu77** [comment]
@LibbyUX Thanks Libby! I'll work on getting those fixes in. As for the footer, I'm not sure how to resolve the issue unless we figure out how it's going to look for smaller screen sizes. The right side menu takes priority and we can't exactly shrink the buttons down, so we're kind of stuck with this for now.

**Comment by LibbyUX** [comment]
@edlu77 thank you so much! Let me iterate on the footer for smaller breakpoints. I'll post updates here and mention you shortly!

**Comment by LibbyUX** [comment]
Hi @edlu77! Would something [like this](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?type=design&node-id=5629-17897&mode=design&t=bG7ZmGu5zCmpRg5z-4) work for 1440x900 and 1280x832? Starting at a width of 1279px, users will see the [resolution notice](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=3262-16459&mode=design&t=8dVOg8YUf6dIytYZ-4) and a vertical/horizontal scroll bar for the entire app page, as we specified for the Cell Distance Explorer. No worries if this is out of scope, however.

We do need to use those buttons in the footer. I could move them up to the header, potentially, if we need to move faster for this milestone. Let me know if further iterations are needed. Looking forward to hearing your thoughts!

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/8834814a-c25d-43d1-992a-049f41075c17)
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/5af84c65-aa4b-461b-8257-ab7120aa39d9)

**Comment by edlu77** [comment]
Thanks! These look pretty good. There probably isn't time to fully implement those breakpoints right now but it shouldn't be too big of a hurdle to adjust the footer.

**Comment by LibbyUX** [comment]
Sounds good, let's try to adjust the footer first. Let me know if we need to move the buttons if the footer resizing doesn't work out and I can design more possibilities. Thanks so much, @edlu77!

**Comment by LibbyUX** [comment]
Hi @edlu77 !

Thanks for pinging me earlier with the review links. We are getting closer!

### Main build review
- Thank you for making the footer responsive! The footer is good to go now for this milestone.
- I still can't access the source data area on my 1920x1080 Google Chrome browser with 100% zoom. Scrolling in this area is not possible at the moment with a 100% view. I have to zoom out to see the source data area:
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/3f9cfcef-e35d-4a7b-8b4c-ab6431a1130a)
![D2AC3264-39A3-4267-B32B-828F66141176](https://github.com/hubmapconsortium/hra-ui/assets/97060856/53d5f910-3322-404a-8e82-686c6a4dcc37)

### Small web component review
- On hover, I receive text not in a card. Is it possible to fix this?
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/a0bb1666-42a6-4ac9-a610-e1f422bf8eb9)

**Comment by LibbyUX** [comment]
@edlu77 thanks for passing the build back to me today and thank you so much for knocking out all of these improvements! They all look great!

I am iterating on some tiny aesthetic updates for certain breakpoints for both the full app and the small wc [here](https://www.figma.com/design/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?node-id=5682-17450&t=H7dW4zx3tZxhHAUF-4). I should have more information tomorrow! Thank you!

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/6d158a80-467b-40f4-9d4d-9351a592e6c3)

**Comment by bherr2** [comment]
Nope! Thanks for working closely and getting this done team!

**Comment by bherr2** [comment]
I'll close this after @axdanbol has had time to finish his code review and merged the PR #334
