### ISSUE TITLE
MVP2 Header

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#329]
# MVP2 Header
### UX Modifications
- FTU Explorer logo button: routes to landing page
- Using the FTU Explorer button: routes to the landing page UI annotation section
- Contact button: opens contact modal overlay with background
- HRA logo button: routes to the HRA Portal by opening this page in a new tab
### UI Modifications
- Aesthetic updates: Padding, spacing, color styles, and font updates
- Additional buttons
- New logos for the FTU Explorer and the HRA Portal

## Resources
- [Prototype Presentation](https://www.figma.com/proto/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?page-id=5058%3A64857&type=design&node-id=5182-85859&viewport=-26029%2C666%2C1.13&t=1oECOUe4JUuO8p6b-1&scaling=scale-down&starting-point-node-id=5182%3A85859&show-proto-sidebar=1&mode=design)
- [MVP2 Local Header Component](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?type=design&node-id=5405-16344&mode=design&t=JWPN9WDhEUpQDbXi-4)
- [HRA Design System](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=103-4&mode=design)

## MVP2 versus MVP1

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/38c677ba-35fa-4be6-b5cb-189b31e6df5e)

**Comment by libby-maier** [comment]
Just a heads up, I made small modifications to the header, so that it would better match the design system, instead of using locally created components in the FTU Explorer Design file. I will edit the above with new links/screenshots today.

**Comment by LibbyUX** [comment]
This is not feasible for this cycle and more design updates will occur to this component. We will revisit in Y3. Thanks!
