### ISSUE TITLE
FTU Explorer: Landing page

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#333]
# MVP2 landing page
- [Figma Design File](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?type=design&node-id=5182-85859&mode=design&t=4UT25EYkddPWNt4F-4)
- [Figma Prototype Presentation](https://www.figma.com/proto/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?page-id=5058%3A64857&type=design&node-id=5182-85859&viewport=-26029%2C666%2C1.13&t=nlALxco72Nv6Izcm-9&scaling=scale-down&starting-point-node-id=5182%3A85859&show-proto-sidebar=1)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/704150e9-be4c-4d98-ade5-740e5970749f)
## Design Updates
- Aesthetic updates for color styles, fonts, padding, spacing, drop shadows, buttons/button states
- New section for the [FTU Explorer UI Annotation](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?type=design&node-id=5182-86049&mode=design&t=4UT25EYkddPWNt4F-4)
  - Clicking the "Using the FTU Explorer button" in the header scrolls down to this section.
    - Note that it is an animated scroll. Details about the animation can be viewed in the below screenshot.
    - Note that the annotation image will need to responsively resize. This is sourced from the [FTU Explorer UI Annotation Figma file](https://www.figma.com/file/GIKR3xb5vAUgaEuxloZwpM/UI-Annotations?type=design&node-id=429-209&mode=design&t=76ERGwPDRrJZZXGv-4). 
    - Note that I will have to redo this graphic with the updated interface after development has implemented all changes for MVP2.
- A footer has been added.
- Per usual, all external links must open in new tabs, as prototyped.
- [Several breakpoints](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?type=design&node-id=5238-102301&mode=design&t=4UT25EYkddPWNt4F-4) have been designed to show how this page should respond to different screen/browser sizes.

## Resources
- Design System: Component Library
- Design System: Style Guide
- Component: In-text link button with states
- [Local Components: FTU Library List](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?type=design&node-id=5213-12370&mode=design&t=4UT25EYkddPWNt4F-4)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/de413540-4a7a-4a48-9f58-92b6a7a5905d)

**Comment by libby-maier** [comment]
# Design update
- Heads up @edlu77 - I am making small aesthetic changes to the footer to keep it more consistent with our other interfaces!
- Ushma and I added a similar but freshly styled footer component for our apps. The functionality is still the same but the styling has been modified.

## Resources
- [Figma Design System file: App footer component](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=2863-4503&mode=design&t=Uh0mpDL1xV5dw9bx-4)
  - See component notes/variants for breakpoints and uses for different variations of this component
- Figma design file - 1920px breakpoint: [FTU Explorer footer implementation](https://www.figma.com/file/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?type=design&node-id=5332-14337&mode=design&t=4P5jRHT9mq8QHgbh-4)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/5a365b64-d849-4017-bd0a-9ba6b9be6472)

**Comment by LibbyUX** [comment]
More design work will occur on the landing page in Y3.

**Comment by LibbyUX** [comment]
Things will change. Closing for now to remove stale requests.
