### ISSUE TITLE
CDE: Landing Page

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#336]
# CDE Landing Page

## User Stories
- As a pediatric pathologist, I want single-cell data, in order to improve disease diagnosis.
- As a user, I need a visually interesting landing page, so I am eager to explore the rest of this website.

## Resources
- Design File: [Landing](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=584-11925&mode=design&t=eaLguGfo9tBkhEw0-11)
- Prototype Presentation: [Landing](https://www.figma.com/proto/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?page-id=1%3A25&type=design&node-id=584-11925&viewport=274%2C398%2C0.05&t=BQ0RtqoRVTcJhkVs-1&scaling=scale-down&starting-point-node-id=584%3A12056&mode=design)
- HRA Design System: [Component Library](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=103-4&mode=design)
- HRA Design System: [Style Guide](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=0-1&mode=design)

## Components
Some components are local, while others are sourced from the HRA Design System.
- [Website header](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=584-16368&mode=design&t=eaLguGfo9tBkhEw0-4)
- [Splash section](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=584-11927&mode=design&t=eaLguGfo9tBkhEw0-4)
  - [Visual cards](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=2919-8823&mode=design&t=23xgUqpsnYqdAfWq-4)
- [VCCF section](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=584-11935&mode=design&t=eaLguGfo9tBkhEw0-4)
- [Footer](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=2762-3953&mode=design&t=23xgUqpsnYqdAfWq-4)

## Landing Page Breakpoints
- [1920px](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=584-11925&mode=design&t=P9WNFK5youlYfBxk-4)
- [1440px](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=708-3150&mode=design&t=P9WNFK5youlYfBxk-4)
- [1280px](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=718-13003&mode=design&t=P9WNFK5youlYfBxk-4)
- **Note**: Any width smaller than 1280px, starting at 1279px, will receive a screen size notice before viewing or creating a visualization
- [1012px](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=718-15119&mode=design&t=P9WNFK5youlYfBxk-4)
- [768px](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=732-16268&mode=design&t=P9WNFK5youlYfBxk-4)
- [544px](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=811-21441&mode=design&t=P9WNFK5youlYfBxk-4)
- [320px](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=811-22399&mode=design&t=P9WNFK5youlYfBxk-4)

## UI 1920px on 3.29.2024

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/aee59165-ee1e-4ae3-a3d6-bbf3ca70fcdf)

**Comment by libby-maier** [comment]
Clicking the secondary VCCF Poster should open a PDF viewer for this file: [VCCF_March2024.pdf](https://github.com/hubmapconsortium/hra-ui/files/14828432/VCCF_March2024.pdf)

**Comment by LibbyUX** [comment]
### Edit notice:
- Updated original comment with breakpoint links in the Cell Distance Explorer design file.

**Comment by LibbyUX** [comment]
Hi @axdanbol, @bhushankhope, and @edlu77!

I am unsure who to assign so I'm pinging the crew. I caught something on a second pass of the CDE landing page. This button should open a PDF viewer for the VCCF poster (see my [above comment](https://github.com/hubmapconsortium/hra-ui/issues/336#issuecomment-2030536988) from April 1). Let me know if you have any questions!

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/e847ec9c-e71a-4143-a318-16f40e877d25)

**Comment by bherr2** [comment]
To be clear, we can add the link but we will not embed a PDF viewer. We'll let the browser render it as if it were any other link.

**Comment by LibbyUX** [comment]
Thank you, @bherr2!
