### ISSUE TITLE
CDE: Vis App

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#344]
# CDE MVP1: Vis App

## User Stories
- As a pediatric pathologist, I want single-cell data, in order to improve disease diagnosis.

## Resources
- Design File: [Vis App 1920px](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=584-12139&mode=design&t=bgmiG3vgdAwXQihE-4)
- Prototype Presentation: [Vis App](https://www.figma.com/proto/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=1-25&viewport=-2119%2C2133%2C0.42&t=bgmiG3vgdAwXQihE-0&scaling=scale-down&starting-point-node-id=584%3A12139&show-proto-sidebar=1)
- HRA Design System: [Component Library](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=103-4&mode=design)
- HRA Design System: [Style Guide](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=0-1&mode=design)

## Main Components
- [CDE App header](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=550-11480&mode=design&t=bgmiG3vgdAwXQihE-4)
- [Tooltip hover cards](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=605-26344&mode=design&t=bgmiG3vgdAwXQihE-4)
- [Metadata Information module](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=584-12575&mode=design&t=bgmiG3vgdAwXQihE-4)
- [Cell Types module](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=811-20240&mode=design&t=bgmiG3vgdAwXQihE-4)
  - [Cell Types listings](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=516-29144&mode=design&t=bgmiG3vgdAwXQihE-4)
- [Visualization module](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=823-24371&mode=design&t=bgmiG3vgdAwXQihE-4)
- [Histogram module](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=811-20895&mode=design&t=bgmiG3vgdAwXQihE-4)
- [Color picker](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=3073-4836&mode=design&t=8EPtFqgDkrA5suJG-4)
  - [Color format](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=3073-4855&mode=design&t=8EPtFqgDkrA5suJG-4)
  - This color picker is modeled after the NXG color picker. I have styled it and made it more simple. I do not want default colors. Users should just simply see the color they've clicked when they click a color swatch.
- [Snackbar](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=615-27824&mode=design&t=bgmiG3vgdAwXQihE-4)
- [Resolution notice modal](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=3262-16459&mode=design&t=8EPtFqgDkrA5suJG-4)

### General Design & Interaction Notes
- Use the Figma prototype tab in the design file to better understand interaction details.
- Please interact with the prototype preview to experience the expected behavior and states. 
  - Sometimes Figma prototypes glitch out, so just ask if you have any questions.
- The app needs to be both beautifully and intuitively responsive to many varying screen sizes.
  - Use horizontal and vertical scrollbars on the entire page as needed for anything smaller than a 1279px screen size. This app is best viewed with a breakpoint of 1280px and above.
- Sometimes design work moves quickly: Inconsistencies, copy-pasta, or errors may be found during development. Please just reach out to me if you have questions!
### Visualization module
- Study participants wanted a pure, pitch-black, #00000 background. Please use this color instead of what is currently in the concept build.
- Future versions note: Users need options eventually to change the background color.
- Starting in the 1012px breakpoint, either the histogram or the visualization module can be opened at one time. Clicking the expand icon on either will collapse the other to make room for the expanded component.
### Module behavior
Users can expand and collapse certain modules with the expected behavior:
- Metadata: When collapsed, the Cell Types list expands.
- Histogram: When collapsed, the Visualization module expands.
- Breakpoints to note:
  - [1440px](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=708-4185&mode=design&t=bgmiG3vgdAwXQihE-4): Metadata is collapse by default.
  - [1280px](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=708-5644&mode=design&t=bgmiG3vgdAwXQihE-4): Metadata is collapsed by default & the histogram has a smaller fixed height.
### Metadata module variations
- The sample metadata module is used for our example visualizations. Users will click on the sample links and see a Google Sheet of the visualized data in a new tab.
- The metadata module is used for user-generated visualizations.

### Download buttons
- All files downloaded will trigger a snack bar notifying the user that the download has been completed.
- Sample data will need to be provided for sample downloads/visualization downloads. I speculate we can rely on Yash and Katy to tell us more about these details. Reach out to me if you have questions and I will get a group conversation going on it.

### Open in New
- Every link on the visualization page should open in a new tab, including those within the app itself. This is so that the visualization that users have created is preserved until they close their browser.

### Exit Notice
- I will design an exit notice for user-generated visualization app pages. This will be similar to the RUI's. I don't have that design right now, but please plan for this functionality.

## Breakpoints & Responsiveness
On breakpoints larger than 1920px by 1080px, both the vis module and histogram should expand. All other components have fixed heights/widths.
- [1920px](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=584-12139&mode=design&t=bgmiG3vgdAwXQihE-4)
- [1440px](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=708-4185&mode=design&t=bgmiG3vgdAwXQihE-4)
- [1280px](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=708-5644&mode=design&t=bgmiG3vgdAwXQihE-4)
  - Responsive Notes: 
    - Any width smaller than 1280px, starting at 1279px, will receive a [resolution notice modal](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=3262-16459&mode=design&t=8EPtFqgDkrA5suJG-4) before viewing or creating a visualization.
    - This app should be full screen without horizontal and vertical scroll bars through 1280x832 resolutions. Starting at widths of 1279px and heights of 831px: Horizontal and vertical scrollbars are needed.
- [1012px](https://www.figma.com/file/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?type=design&node-id=823-25222&mode=design&t=bgmiG3vgdAwXQihE-4)

# 1920px on 4.5.2024
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/ca188d6e-bcdc-4f13-a21d-f72d2d65cb4a)

**Comment by LibbyUX** [comment]
@bherr2 @edlu77 @axdanbol @bhushankhope 

Is it possible to use the same exit notice functionality from the RUI after people:
- try to close the vis app after they have altered the colors of an example visualization
- try to close the vis app after they have created a visualization

RUI exit notice on Google Chrome + MacBook Pro:

<img width="1380" alt="Screenshot 2024-06-06 at 12 47 21 PM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/8a782d41-8a93-4278-b554-9bb102c79d94">

**Comment by LibbyUX** [comment]
@bherr2, @axdanbol, @edlu77, & @bhushankhope -

Is it possible to lock the scale bar at the bottom right of the visualization module? It will still rotate in 3D, but having a fixed location for it will provide an improved user experience. Let me know! Thank you!

**Comment by bherr2** [comment]
Not for this release. The module we're using was really only designed for 2D. To do it properly in 3D will require much more development time than we have left. Please put on the roadmap for a future MVP.

**Comment by LibbyUX** [comment]
Perfect, I will add to future versions. Thank you, @bherr2!
