### ISSUE TITLE
User stories updates

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#354]
# User stories updates
Update existing user stories. Add four new user stories to the Human Reference Atlas. 

## Design to do
- [x] Complete title, description, overview, and iconography updates for old user stories.
- [x] Reach consensus on titles, descriptions, overviews, and iconography for new user stories.
- [x] HRA-M10-4 spec is approved

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/77661bb3-3579-4fbc-8068-d2755e3b213d)

### Add new user stories pages
All user stories pages have placeholder content currently. We will use a screenshot for Dashboards and the other 3 user stories will have video content (see #359 for content delivery details).
- [x] Add [FTU Explorer page](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5487-33263&t=TwGG2eKkT7bnPNIJ-4)
- [x] Add [Cell Distance Explorer page](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5508-13306&t=TwGG2eKkT7bnPNIJ-4)
- [x] Add [Atlas Components page](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5508-13466&t=TwGG2eKkT7bnPNIJ-4)
- [x] Add [Dashboards page](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5508-13624&t=TwGG2eKkT7bnPNIJ-4)

## Resources
- Figma Design File: [Global Navigation Component](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---6th-(v1.5)?type=design&node-id=5487-30144&mode=design&t=qL0eoSZa5sxkRwo8-4)
- Figma Design File: [Use the HRA Overview Page](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?type=design&node-id=5487-30473&mode=design&t=fM4hIse6d7n2KkB4-4)
- Figma Design File: [User Stories Components](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?type=design&node-id=5531-16221&mode=design&t=fM4hIse6d7n2KkB4-4)
  - This is the source of truth for titles, descriptions, and iconography.
- Figma Design File: [New User Story Pages](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5571-8737&t=TwGG2eKkT7bnPNIJ-4)
- [Former GitHub Issue](https://github.com/cns-iu/humanatlas.io/issues/398)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/4c02d522-f7c3-4954-9d0f-84bf1e0253d3)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/27a94351-97de-47fe-a3ab-4baea7bda9e0)

**Comment by LibbyUX** [comment]
@bherr2 & @bhushankhope - These tasks are ready for development. Thank you!

**Comment by LibbyUX** [comment]
I edited and consolidated [this comment](https://github.com/hubmapconsortium/hra-ui/issues/354#issue-2261339849) with #368. The spec for HRA-M10-4 is approved and it is ready for development!

**Comment by LibbyUX** [comment]
Hey @bhushankhope & @bherr2, just a heads up: there were minor adjustments to the [overview text content on the FTU Explorer page](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5487-33270&t=Xhiz3sNCTo32M8xK-4) while I was out of the office. You can read the comment thread between Katy & I [here](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s?node-id=5487-33263#812997403). This is still developing and I will follow up on this issue when it is finalized.

**Comment by LibbyUX** [comment]
The FTU Explorer overview text has been finalized with @katyb. Please see the [FTU Explorer overview text](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5487-33270&t=Xhiz3sNCTo32M8xK-4) for this update.

**Comment by LibbyUX** [comment]
Hey @bhushankhope, I have updated your to-do list based on new information from today. I peeked at the build preview just now for this issue. Please let me know if you have any questions:

## Dev to do with links to Figma
### Global navigation component
- [ ] [Training & Outreach menu](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5487-30224&t=vjGqezhZm3WN1rl3-4): Remove the menu item HRA User Stories
- [ ] [Use the HRA menu button name update](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5487-30280&t=vjGqezhZm3WN1rl3-4) (added 6/12): Update from Use the HRA to **Use HRA Previews**
- [ ] Use HRA Previews menu: Update verbiage from "Overview: HRA Use Cases" to "[Overview: Use HRA Previews](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5542-19255&t=vjGqezhZm3WN1rl3-4)"
- [ ] Use HRA Previews menu: [Add Preview: before every title](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5542-19299&t=vjGqezhZm3WN1rl3-4).
- [ ] Tools menu: [Add Preview: FTU Explorer and Preview: Cell Distance Explorer](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5542-19300&t=vjGqezhZm3WN1rl3-4). Route to user story pages.
### Overview: Use the Atlas page
- [ ] Update page title from Use the Human Reference Atlas to [Use Human Reference Atlas Previews](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5487-30477&t=vjGqezhZm3WN1rl3-4)
- [ ] Add [new paper banner card](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?type=design&node-id=5491-10163&mode=design&t=fM4hIse6d7n2KkB4-4).
- [ ] Rename [all button cards](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5487-30484&t=vjGqezhZm3WN1rl3-4) to start with Preview: [title]
### Overview: Tools page
These button cards route to the user story pages.
- [ ] Add [Preview: FTU Explorer button card](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5542-19173&t=vjGqezhZm3WN1rl3-4)
- [ ] Add [Preview: Cell Distance Explorer button card](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5542-19183&t=vjGqezhZm3WN1rl3-4)

**Comment by bhushankhope** [comment]
Updated above content in PR #399. Can be previewed [here](https://666af2d4e5d72b2d9bcf817b--hra-ui.netlify.app/apps/humanatlas.io/)

**Comment by LibbyUX** [comment]
Thanks so much, @bhushankhope, this looks excellent. We are super close!

Two requests:
- Can you fix the titles on the Overview: Tools page to have the [Preview:] leading before the title of FTU/CDE?
- Can you add a max width to the [menu flyout for Use HRA Previews](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5542-19254&t=iEAUn434haojVF7L-4)? I'd like to see the text on one line.

<img width="1580" alt="Screenshot 2024-06-13 at 10 50 29 AM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/5d5004e4-0de3-48bd-bafe-ceba9a70e486">

**Comment by bhushankhope** [comment]
@LibbyUX increased width and added preview: to the card titles

**Comment by LibbyUX** [comment]
@bhushankhope it looks great!

One last request and this can be closed: 
- Can you please add Preview: [US Title] to every title card for the user stories pages? This was a last-minute update, see the [Figma canvas](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5571-8737&t=Yra3Sl60JonOhwhT-4)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/55017c82-f522-4dba-8c31-b02f8a893a86)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/e4d1bf48-1c35-4f9d-aea8-2f7a7f62c6b7)

**Comment by LibbyUX** [comment]
@bhushankhope - We have been communicating via Slack on this but here's another update:
### FTU Explorer page
[View Figma](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5982-3679&t=Yra3Sl60JonOhwhT-4)
- [ ] Add a section header: FTU Explorer Features
- [ ] Update optimized graphic (see attached)

### Dashboards page
[View Figma](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5982-3607&t=Yra3Sl60JonOhwhT-4)
- [ ] Add a section header: Preview: Diversity & Inclusion Dashboard
- [ ] Update optimized graphic (see attached)


![FTU MVP2 - 6 14 2024](https://github.com/hubmapconsortium/hra-ui/assets/97060856/d2dd6803-3d21-4537-a0bd-67517534954f)
![HRA Dashboard_ Diversity   Inclusion - 6 14 2024](https://github.com/hubmapconsortium/hra-ui/assets/97060856/4db4e7cf-d260-43b2-9140-03c69ba43aa9)

**Comment by bhushankhope** [comment]
@LibbyUX merged into develop in pr #440

**Comment by LibbyUX** [comment]
Perfect, thank you @bhushankhope ! Closing this out!
