### ISSUE TITLE
humanatlas.io content: demo videos for new user stories

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#359]
# humanatlas.io content: demo videos for new user stories
User stories/pages that could benefit from having demonstration video content:
### humanatlas.io
- US#4 page: FTU Explorer
- US#5 page: Cell Distance Explorer
- US#6 page: Use Atlas Components
### Cell Distance Explorer
- Cell Distance Explorer: Interface Guide/Help Page
  - See related issue: #343

## Questions
- Who is accountable for filming, editing, uploading, and delivering URLs for these demo videos?

## Figma Resources
- [US#4 page: FTU Explorer](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?type=design&node-id=5487-33263&mode=design&t=fM4hIse6d7n2KkB4-4)
- [US#5 page: Cell Distance Explorer](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?type=design&node-id=5508-13306&mode=design&t=fM4hIse6d7n2KkB4-4)
- [US#6 page: Use Atlas Components](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?type=design&node-id=5508-13466&mode=design&t=fM4hIse6d7n2KkB4-4)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/7bf03b3f-30e4-4fcf-b03c-e159e7d7eca2)

**Comment by LibbyUX** [comment]
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/050d5064-0d59-4b54-bb4d-baccbddead24)

**Comment by LibbyUX** [comment]
Hi team,

I have contacted @andreasbueckle & @bherr2 about this demo video content. 

Three people have been recommended to create demonstration videos for the new user story pages on the HRA Portal. The videos will be captured after the development team implements the UIs for these user stories. 

I received the following recommendations:
- @supriyabidanta - US#4 Functional Tissue Unit Explorer
- @J-Yash - US#5 Cell Distance Explorer
- @axdanbol - US#6 Lightweight Atlas Components

View example production user story webpages with Andi's demo videos:
- [US1: Improve Cell Type Annotations](https://humanatlas.io/user-story/1)
- [US2: Predict 3D Spatial Origin of Tissue Samples](https://humanatlas.io/user-story/2)

The demo videos are due no later than June 14th. Please let me know if this is feasible with your workload! We will closely track development progress, so this video content can be created as soon as the interface is ready.

Please reach out with questions if you have them!

**Comment by andreasbueckle** [comment]
Let me know if you need help setting up OBS for screen-recording.

**Comment by LibbyUX** [comment]
@J-Yash @supriyabidanta @axdanbol:

Please let @andreasbueckle and me know if you have any questions about creating these demo videos. Thank you!

**Comment by andreasbueckle** [comment]
@J-Yash 
If you are uncomfortable with recording a video, I am happy to make the one for the Cell Distance Explorer.

**Comment by J-Yash** [comment]
> @J-Yash If you are uncomfortable with recording a video, I am happy to make the one for the Cell Distance Explorer.

@andreasbueckle Thank you! That would be great. Please let me know if you need anything from me.

**Comment by andreasbueckle** [comment]
Cell Distance Explorer is at https://664b6ba8d8a3d0d7cb6cc4f9--hra-ui.netlify.app/ (select `cde-ui`).

**Comment by bherr2** [comment]
The `cde-ui` is NOT ready to be used/reviewed _at all_. We'll update as we get closer to release.

**Comment by andreasbueckle** [comment]
Thanks for the note. I needed the link to start familiarizing myself with the in-progress interface so I can prepare my demo. Will not share further.

**Comment by LibbyUX** [comment]
Noted, thank you both!

**Comment by LibbyUX** [comment]
Hi @bhushankhope,

@andreasbueckle has delivered a video for the CDE page: https://www.youtube.com/watch?v=q8zCRd7vHH8

I am making png files for the other 3 use cases now. I will add to Figma. Thank you!

**Comment by LibbyUX** [comment]
@bhushankhope please see all [visual content in Figma](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5571-8737&t=LH0GFY6YdR0Z1PgJ-4). Thanks so much!

**Comment by LibbyUX** [comment]
I am moving this to QoL improvements. Thanks!

**Comment by LibbyUX** [comment]
Videos may be needed in December to demonstrate new functionality for 8th release UIs. I will request videos for individual UIs as needed.
