### ISSUE TITLE
7th release notes (v2.1)

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#362]
# 7th release notes (v2.1) content
Let's use Figma as the source of truth for the release notes content this release. We are tightening the categories this release cycle, to keep it concise for the rebrand of the HRA.

@bherr2, @andreasbueckle, & @katyb, please:
- Review my first pass and comments in the Figma design file: [7th Release Notes](https://www.figma.com/file/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?type=design&node-id=5487-29673&mode=design&t=4NxszO0L1GEPt728-4)
- Take your first pass at commenting on the release notes: Provide feedback and your expectations for these sections. Feel free to drop links and attachments in Figma comments.

Is there anyone else we should loop in for this content?

Thanks!

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/ce79b389-a7b3-455b-bb77-36aa8fd3b36e)

**Comment by LibbyUX** [comment]
Sorry for the unassign/reassign ping, @bherr2! I was trying to add Bhushan and misclicked. 

I will summarize our progress for the group now in my next comment.

**Comment by LibbyUX** [comment]
## 7th Release Notes progress
**Caution: The body content for this page is still being updated in both Figma and the build:**
- @andreasbueckle to update the HRA Diversity Survey 2024 section directly.
- @bherr2 to add counts to the Data section directly.
- @katyb & Lisel still need to review Figma.
- Katy still needs to approve the UX copy in Figma.

Fast adjustments will occur today, tomorrow, and on Friday. I will provide updates as needed for @bhushankhope. Thanks so much, team!

**Comment by andreasbueckle** [comment]
Thanks @LibbyUX, I will update the YAML file @bhushankhope pointed me to.

**Comment by LibbyUX** [comment]
@bhushankhope SOP updates have been finalized in the S[OPs section of Figma](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5487-29723&t=P89gfkRNj3DXY6m8-4). Thanks!

**Comment by LibbyUX** [comment]
@bhushankhope, I added VHMOOC URL in [VHMOOC section](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5895-16167&t=P89gfkRNj3DXY6m8-4):

<img width="553" alt="Screenshot 2024-06-13 at 12 32 08 PM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/2660ec2c-ac69-4f1e-b0b5-ddeb00944c73">

**Comment by LibbyUX** [comment]
@bhushankhope - This is looking good. 

One last request on my end - Is it possible to remove the spaces between these listed bullet items?

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/e3a71728-cd46-4ebe-8457-87be05e5bffa)

**Comment by bhushankhope** [comment]
@LibbyUX About the spaces, I am using that component in other pages where the spacing is required. Let me check with daniel if we can find some solution. I will let you know. Thanks

**Comment by LibbyUX** [comment]
Sounds great! It's interesting because the New Digital Object list doesn't have it. I appreciate you checking with @axdanbol!

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/d9edcc8e-4ece-4684-9c28-758798204385)

**Comment by bhushankhope** [comment]
@LibbyUX I am not doing anything different, let me see what is causing it😅. Thanks

**Comment by LibbyUX** [comment]
It looks great now, @bhushankhope! Thank you!
