### ISSUE TITLE
3D anatomical structures component

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#374]
# 3D anatomical structures animation
- GIFs are needed for the HRA Dashboard specification's Data page.
  - Male and female organ expansion and collapsing, ideally in a perfect loop.

## Resources
- Figma comment thread: [Animation discussion](https://www.figma.com/file/GAHPA5ni25Oq6qjeypvacx?type=design&node-id=2051-675&mode=design#789435080)
- Figma design file: [Data Dashboard](https://www.figma.com/file/GAHPA5ni25Oq6qjeypvacx/Dashboards?type=design&node-id=2051-675&mode=design&t=X0UPB0cOT9NBe8bg-4)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/0486291e-72bd-4152-91e9-7a91c580bee3)

**Comment by andreasbueckle** [comment]
@LibbyUX 
Can you please also tag Ushma in this TODO? I will work with her.

**Comment by LibbyUX** [comment]
Yes, @andreasbueckle! I will assign her as soon as she accepts the invite for this repository. Thanks so much!

**Comment by LibbyUX** [comment]
Per conversations today: we may use the organ icons that Ushma has designed. More on this before EOB May 10th.

**Comment by LibbyUX** [comment]
Update: This issue may be closed as not planned.

We are not doing animations for this component, and we may not have this component at all. I will follow up here as the flexible spec evolves for Dashboards.
