### ISSUE TITLE
Splash text content update

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#396]
# Remove NeMO from splash content

Hey team, there was a misunderstanding about the data providers, so we need to update our splash content for the FTU Explorer. NeMO is not a data provider, so please remove them from the dataset entities in the last sentence. Thank you!

I am mentioning @bherr2 & @edlu77 for visibility. Thanks so much!

### Figma
- [FTU Explorer Landing Page](https://www.figma.com/design/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?node-id=5182-85937&t=lXF1Zu2sWGTnIppv-4) with updated splash text content
- [Comment thread in HRA 7th Release](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s?node-id=5487-33263#812997403) between Katy & Libby on dataset providers

### Updated text splash content
> A functional tissue unit (FTU) is the smallest tissue organization that performs a unique physiologic function and is replicated multiple times in a whole organ. Explore medical illustrations of FTUs to view cell type populations by gene, protein, and lipid biomarkers. The FTU Explorer features experimental datasets from HuBMAP, CellxGene, and GTeX.

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/5b2a6a7c-ce55-471e-8486-b27ccd869ec6)

**Comment by edlu77** [comment]
Should I go ahead and make these changes @bherr2 ?

**Comment by LibbyUX** [comment]
Please reach out if you have any questions! 

Katy and I sat together yesterday to finalize this splash text content.

Thanks for helping us stay consistent with our messaging!

**Comment by bherr2** [comment]
@edlu77 yes please

**Comment by edlu77** [comment]
Changes have been added!
