### ISSUE TITLE
CSV Files - 7th Release

### ISSUE THREAD

**Issue by bhushankhope** [hubmapconsortium/hra-ui#398]
Hi Bruce, I need the CSV files for 
- [x] [ASCT+B Tables](https://github.com/hubmapconsortium/hra-ui/blob/main/apps/humanatlas.io/src/assets/table-data/asctb_release6.csv)
- [x] [VCCF](https://github.com/hubmapconsortium/hra-ui/blob/main/apps/humanatlas.io/src/assets/content/pages/vccf.yaml#L40)
- [x] [FTU Illustrations](https://github.com/hubmapconsortium/hra-ui/blob/main/apps/humanatlas.io/src/assets/table-data/ftu-cell-count.csv)
- [x] [3D Reference Objects](https://github.com/hubmapconsortium/hra-ui/blob/main/apps/humanatlas.io/src/assets/table-data/as-per-organ.csv)
- [x] [OMAPs](https://github.com/hubmapconsortium/hra-ui/blob/main/apps/humanatlas.io/src/assets/table-data/omaps_release6.csv)

**Comment by bherr2** [comment]
Nevermind, I'll figure it out. I'll make a PR for the data updates. But I'll go ahead and do the updates for the pure data changes for humanatlas.io.

**Comment by bhushankhope** [comment]
@bherr2 I have linked the csv files, I have updated the issue.
There is no csv file for the vccf page, we have written the data in yaml file itself
