### ISSUE TITLE
Changing cell type color only works one-way

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/hra-ui#415]
In the CDE, when changing the color of a cell type via the *interactive legend in the histogram*, the color scheme in the *Cell Types pane* on the left is not auto-updated: 

Before: 
![image](https://github.com/hubmapconsortium/hra-ui/assets/22821046/8f15f5d4-2069-4871-a009-b52a50446ddf)

After changing color for CD68 to blue in *interactive legend for histogram*: 
![image](https://github.com/hubmapconsortium/hra-ui/assets/22821046/3cd486f8-63aa-4509-85db-4af9e12b324c)

Expected behavior: 
The color should be updated. It works the other way, i.e., when changing the color in the Cell Types pane:

Before: 
![image](https://github.com/hubmapconsortium/hra-ui/assets/22821046/6ac481ce-0b79-46cf-b19f-f674082a5f78)

After changing color for CD68 to blue in *Cell Types pane*: 
![image](https://github.com/hubmapconsortium/hra-ui/assets/22821046/bf3ce92b-e0a7-41b6-bbe2-e8464095992c)

**Comment by axdanbol** [comment]
I took a quick look at this and there seems to be some change detection bug. As soon as I hover over the cell types portion of the app the color updates to the correct one.

**Comment by bhushankhope** [comment]
fix in pr #426
