### ISSUE TITLE
Update favicons for all apps to the HRA favicon

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/hra-ui#418]
CDE has this already, but Dashboard does not. Check all other apps to to be consistent.

**Comment by LibbyUX** [comment]
Please use the [small-scale logo variant](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=2191-1748&t=9NfkyryKlvwsOW5X-4) for the favicon. Thank you!
