### ISSUE TITLE
Updates to HRA Organ Gallery page

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#430]
# Updates to HRA Organ Gallery page

@andreasbueckle, I am requesting updates for the HRA Organ Gallery [page](https://humanatlas.io/organ-gallery-in-vr)/title:
- Rename all instances of Organ Gallery in VR to HRA Organ Gallery throughout www.humanatlas.io
- In the Overview text, remove the last sentence:
  - The app can be downloaded at https://www.meta.com/experiences/5696814507101529
- Replace this sentence with a button "Download App" which routes users to the [HRA Organ Gallery on Meta](https://www.meta.com/experiences/5696814507101529).
  - I believe this is a sufficient call to action to route them to Meta and that we don't need the QR code on the website. What do you think?
- Remove text under Video Demo heading:
  - Please view the video below for a demo of the HRA Organ VR Gallery

@andreasbueckle - Let me know if you approve of these changes and I will submit to development. Thank you!

<img width="1312" alt="Screenshot 2024-06-13 at 12 22 28 PM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/3d8328a5-b55f-4518-ae4e-f1511cde0649">
<img width="991" alt="Screenshot 2024-06-13 at 12 24 50 PM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/55c648e5-43b5-499e-a5ef-4400146b6c30">

**Comment by LibbyUX** [comment]
@andreasbueckle Happy Friday!!!!!

We can work on this next week if you'd like. No rush - Lots happening today for us all!

Have a great day!!

**Comment by andreasbueckle** [comment]
@LibbyUX 
- 👌 Yes, please rename all instances of Organ Gallery in VR to HRA Organ Gallery throughout [www.humanatlas.io](http://www.humanatlas.io/)
- 👌Yes, please remove the last sentence in the overview text:
        The app can be downloaded at https://www.meta.com/experiences/5696814507101529
- 👌Yes, please replace this sentence with a button "Download App" which routes users to the [HRA Organ Gallery on Meta](https://www.meta.com/experiences/5696814507101529).
- 👌Yes, no QR code required.
- ❗Please remove the entire *Video Demo* section as the video is completely outdated. Thank you!
- ❗ Please add this reference to the References list:
  - A. Bueckle, C. Qing, S. Luley, Y. Kumar, N. Pandey, and K. Börner, “The HRA Organ Gallery affords immersive superpowers for building and explorring the Human Reference Atlas with virtual reality,” Frontiers in Bioinformatics, vol. 3, 2023. doi: [10.3389/fbinf.2023.1162723](https://doi.org/10.3389/fbinf.2023.1162723)

**Comment by andreasbueckle** [comment]
Yes, let's update to `https://humanatlas.io/hra-organ-gallery`. Could we implement a redirect from `https://humanatlas.io/organ-gallery-in-vr` to `https://humanatlas.io/hra-organ-gallery`? Thanks!

**Comment by bherr2** [comment]
Ok, we'll work on that next week. Please post a new issue for just that change (the other stuff has already made it to production)

**Comment by LibbyUX** [comment]
Thank you all! I submitted #444 and the page looks good. Happy Friday!
