### ISSUE TITLE
Hover tooltip shows Times New Roman instead of Metropolis Medium

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#434]
Please see the [FTU explorer tooltip component](https://www.figma.com/design/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?node-id=5238-102289&t=vh1cyGhM2Ivf0Q4q-4) specified in Figma. Thank you!

<img width="1681" alt="Screenshot 2024-06-13 at 5 26 32 PM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/3f210b25-d4ba-4709-aec8-b0fa6970c393">

<img width="1452" alt="Screenshot 2024-06-13 at 5 13 04 PM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/8cd0e93c-4fab-411b-a245-cf5402d11f00">

**Comment by bhushankhope** [comment]
@LibbyUX update the tooltip font styles [here](https://github.com/hubmapconsortium/hra-ui/pull/469#issuecomment-2176655185). Please review. Thanks

**Comment by LibbyUX** [comment]
Thank you @bhushankhope !
