### ISSUE TITLE
soft launch showing 6th release notes banner?

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#438]
This might be in progress but just wanted to flag it from my end. Thank you!

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/40b7f8ee-3858-471d-a2db-88fb39cbd2f0)

**Comment by bherr2** [comment]
Probably a caching thing. Try to shift+refresh

**Comment by LibbyUX** [comment]
Indeed it was! Thank you @bherr2 !
