### ISSUE TITLE
New HRA font styles

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#439]
I'm inspecting the CDE landing on Google Chrome, and I see the following: 
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/7c756194-0a29-42e0-9ac5-e97a88d00cf8)

This is what I see in Figma:
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/492f5f5c-abf5-4647-aa0f-cd362f88cac5)

Does this match the spec? Also, how can I help make fonts/font weights easier for our team? I know it's been a moving target for us all as we begin using the new design system. Things are starting to get settled and you can see this progress in the Design System Repo: [Pattern Library Typography Style Sheet](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=3739-15606&t=FQZbf1z5LbpL8k6x-4)

**Comment by LibbyUX** [comment]
While working on #452 , I supplied [design notes](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=4269-24264&t=hDK2XRTIVA3mJdUK-4) & side-by-side images while inspecting font styles online vs. in the Figma files. Please see my font design notes from 6.17.2024 for both the cde-ui, dashboards-ui, and all new/updated HRA interfaces.

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/c2d91bac-d767-411d-9e27-e9db77db8d45)

**Comment by edlu77** [comment]
Fonts updated in develop
