### ISSUE TITLE
Zooming in/out menu behavior in Google Chrome

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#442]
The top navigation options reappear when zooming out:

![0EC97164-C744-4AE4-A8ED-D0EE153825A5](https://github.com/hubmapconsortium/hra-ui/assets/97060856/7b2f0649-bfd8-473a-8e21-539d1a43550c)

**Comment by bhushankhope** [comment]
@LibbyUX fixed in pr #468

**Comment by LibbyUX** [comment]
Thank you!
