### ISSUE TITLE
Add pages & button cards for K3 and K4

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#445]
# Add pages for K3 and K4
Two new pages have been written for Kaggle competitions.

## Google Doc & Video Content
- [Kaggle #3: HuBMAP - Hacking the Human Vasculature](https://docs.google.com/document/d/1qyqq-cDhlB9Fx7H63kmODGHucPMZ7aRwrYplp3Zpz2I/edit#heading=h.677m5nz41zzz)
- [Kaggle #4: SenNet + HOA - Hacking the Human Vasculature in 3D](https://docs.google.com/document/d/1ArdrJlk7hlDWe8GKKr135GdMTvNN3W5wqgiQ5v4s6uo/edit#heading=h.677m5nz41zzz)
  - [Award Ceremony](https://youtu.be/OxZOZ_TTq80?si=OdkuX7HVn1ocRmiC) for YouTube Embed

Please let me know if you need any help with this. The expectation is that they are the same as previous Kaggle pages.

## Dev To Do
For both K3 & K4:
- Add K3 page content
- Add K4 page content
- Button card component: Remove open in new icon for K3 & K4
- Button card component: Route K3 & K3 to their new pages

**Comment by bhushankhope** [comment]
@LibbyUX Under the Acknowledgments section, there is one single image of logos combined, is it possible to get separate image of each logo? Thanks

**Comment by LibbyUX** [comment]
@bhushankhope, thanks for the mention. Let me look into this and compare this what we have done previously. I will follow up here with a mention and more info shortly!

**Comment by LibbyUX** [comment]
@bhushankhope - I made updates: We will list the sponsors out, in text, like we do for the other pages. I have edited the Acknowledgements section in the document here: https://docs.google.com/document/d/1ArdrJlk7hlDWe8GKKr135GdMTvNN3W5wqgiQ5v4s6uo/edit#heading=h.gt2186swp8t
