### ISSUE TITLE
Add new HRA favicon

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#451]
HRA Design System: [Small scale variant](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=2191-1748&t=FQZbf1z5LbpL8k6x-4)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/11d13017-47d8-4f55-b0d5-2ec2738dbec6)

**Comment by bhushankhope** [comment]
@LibbyUX all apps now show the favicon. 
https://apps.humanatlas.io/ftu-explorer/#/
