### ISSUE TITLE
Appearance discrepancy in CTA button

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#452]
## Appearance discrepancy in CTA button

The call to action button has rounded corners in `https://apps.humanatlas.io/dashboard`. This button's font-weight and letter spacing could also be closer to the specification.

### Production
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/643ba43f-6da1-48c6-a8b3-651919c52ee2)

### Spec
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/689a8573-948a-4e33-94e4-d57d988f11b4)

### Design System
Please see the [CTA button component](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=1710-7&t=FQZbf1z5LbpL8k6x-4) in the Design System Repository.

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/dd200225-bdf7-4661-bc61-d4b679e00317)

**Comment by LibbyUX** [comment]
@bhushankhope thank you so much! The font sizes have been a moving target this cycle. Last week I adjusted the font size from 18px to 16px in the design system. Thank you for noting this was not yet updated in the Dashboards file! I just refreshed it with the design system repo updates, so you should see those changes in [Dashboards](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=2572-16651&t=NcD8toEhstqgF7CP-4) now.

Yes, please ping me when the button corner radius' and the [label font styles](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=3739-15630&t=hDK2XRTIVA3mJdUK-4) match the spec exactly! There might be more tinkering and we might need to sit together to finalize the font styles in production. Thanks so much for looking into this!

**Comment by bhushankhope** [comment]
@LibbyUX fixed in pr #468
