### ISSUE TITLE
Add FTU data to DOs Per Organ visualization in Data Dashboard

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#459]
@katyb shares a conversation with @bherr2. 

Eventually, we will add FTUs to the [Data Dashboard's](https://apps.humanatlas.io/dashboard/data) Digital Object Per Organ visualization.
 
![image_720](https://github.com/hubmapconsortium/hra-ui/assets/97060856/7c4f532b-d692-43f9-9d04-5932ea7d1716)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/849ec764-425a-4374-b6c8-24218dac9628)

**Comment by bherr2** [comment]
Yeah, I should be able to add it, will need to update my processing, but I can do that when I get time.

**Comment by bherr2** [comment]
Done
