### ISSUE TITLE
Navigation component: Add Preview section to tools menu

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#460]
# Navigation component: Add Preview section to tools menu
- Add a Preview section to the tools menu in the navigation component
- Rename (for this menu only):
  - Preview: Use Atlas Components to **Preview: Atlas Components**
  - Preview: Track Atlas Evolution and Usage to **Preview: HRA Dashboards**
  - Cell Population Graphs to **Preview: Cell Population Graphs**
  - Millitome to **Preview: Millitome**
- Reorder the renamed Cell Population Graph & Millitome menu items to the bottom.

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/45edaf72-df90-4eac-af32-a14d842e627c)

## Figma
- [Nav component: 7th Release](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5536-16733&t=qBy8RRnafpFWWJFp-4)

## Relevant Communication
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/b0cd5bca-e698-47b2-8aca-c216085957f1)

**Comment by LibbyUX** [comment]
Note that I edited Figma and this issue after the CNS UX Specs meeting with @katyb

**Comment by bhushankhope** [comment]
@LibbyUX I have made the changes. Please review [here](https://github.com/hubmapconsortium/hra-ui/pull/465#issuecomment-2176125680)

**Comment by LibbyUX** [comment]
Looks great! I will close this out when it's live. Thank you so much @bhushankhope !
