### ISSUE TITLE
Tools overview page: Reorganize card buttons & add all preview card buttons

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#461]
We are featuring all previews in the tools section as well for increased visibility per #460 

Please reorganize the card buttons and add the rest of the preview card buttons on the Tools overview page.

### Figma
-[ Tools overview](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5487-30425&t=feRGHwkrbD2AtQPv-4)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/e4fda590-a557-49ac-a1f7-25ebc6d53be6)

**Comment by LibbyUX** [comment]
More design work is needed on this today. I will follow up with more details. Thanks!

**Comment by LibbyUX** [comment]
Let me follow up with more details tomorrow on this. Thank you!

**Comment by LibbyUX** [comment]
Ready for dev:
- Add "Preview:" to the titles of Cell Population Graphs and Millitome
- Reorganize the cards to match the global navigation updates for Tools
- Add all new preview UIs

### Figma
- [Overview: Tools](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5487-30425&t=vtTBdpiVipAsOHsj-4)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/33ece046-38bf-4398-9aa8-4921c2fa5291)

**Comment by bhushankhope** [comment]
@LibbyUX  fixed this in PR #464

**Comment by LibbyUX** [comment]
Thank you @bhushankhope !
