### ISSUE TITLE
Reorganize visual button cards & navbar

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#462]
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/8c14236e-316f-4dc2-8f66-18432db3b3d0)

**Comment by LibbyUX** [comment]
Katy mentioned today that this is a lower-priority request.

**Comment by LibbyUX** [comment]
This request is ready for development. 

Please see the areas for this update:
- Design System Repo: 
  - [Visual card buttons](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=3953-16141&t=waRA5FezxZfdwb4n-4)
  - [Nav header](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=3949-18352&t=waRA5FezxZfdwb4n-4)
  - [Mobile menu](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=3960-23061&t=waRA5FezxZfdwb4n-4)
- HRA Dashboards Design File: [Landing Updates 6.19.2024](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=2923-23491&t=wzQr96lzQZxOZmiu-4)

Notes for devs:
- Card images for Publications & Experimental Data have been swapped
- All variations of the card buttons, nav headers, and mobile menus have been reorganized

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/c9129683-3052-4704-99fb-52fa54e81e02)

**Comment by bhushankhope** [comment]
@LibbyUX reorganized cards.
https://apps.humanatlas.io/dashboard/
Thanks

**Comment by bherr2** [comment]
The header doesn't seem to match the card order...

![image](https://github.com/hubmapconsortium/hra-ui/assets/34098595/5f83c9e9-09c2-4cf5-9a87-49d9080178d6)

**Comment by bhushankhope** [comment]
@bherr2 need to merge develop into main. I will create a PR

**Comment by bherr2** [comment]
I merged it manually

**Comment by bhushankhope** [comment]
Thanks

**Comment by bherr2** [comment]
Once https://github.com/x-atlas-consortia/hra-apps/issues/35 is fixed, we should be able to close this.

**Comment by LibbyUX** [comment]
I see this as fixed in the preview, but the live site still needs the adjustment

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/0f394398-9dac-4b95-a65b-22a461401e61)

**Comment by LibbyUX** [comment]
Thank you so much @bhushankhope !
