### ISSUE TITLE
Landing page: Cosmetic & responsive design updates

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#470]
The CDE landing page has been adjusted to be more dynamic and cosmetic. This is a low priority development request. Please see my annotated image and [new section of the MVP1 canvas](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2147-18057&t=xYaOjtb3g7VmYGbF-4) for all adjustments/breakpoints:

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/288e0f4e-6e5e-4364-b908-06cc7b6439bf)

**Comment by LibbyUX** [comment]
Quick update for devs: The [app footer variant](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=2762-3953&t=waRA5FezxZfdwb4n-4), plus all of it's breakpoints, in the design system repo, has been updated to be more dynamic and aesthetic. Changes have been pushed to the CDE and Dashboards design files.

App footer updates for all breakpoints:
- Logo size adjusted
- Label font/sizes finalized (hopefully)
- Medical disclaimer text color updated
- Padding/spacing updated
- Icon buttons (social media + funders) updated

 I hope that this is the last app footer change for a while! I won't be updating it again unless I receive a modification request. Please let me know if there is anything more I can do for this one to make it easier for development. Thanks!

**Comment by LibbyUX** [comment]
@edlu77, Thanks so much for the updates at https://667c32b1d316be6962072132--hra-ui.netlify.app/apps/cde-ui/ - We are super close! The responsive updates are amazing and, in general, it looks fabulous.

I compared Figma and the preview side-by-side in a new [design audit section](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2251-18162&t=9TwZbxqmg2N3cara-4).

I left my requests, questions, and screenshots in the [Notes section](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2256-18330&t=9TwZbxqmg2N3cara-4)

Regarding my font comments: @bhushankhope and I have had difficulties with how the Metropolis font appears online. It always appears thinner in production than how it appears in the spec. Please see my typography sheet [here](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=3739-15606&t=uNRJ0Klo3nHFxkfO-4) and bounce ideas off of me and Bhushan!

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/96a47581-5fde-4a21-8623-e1b594f0a55a)

**Comment by LibbyUX** [comment]
Hey @edlu77 can you send me the most recent preview link to this?

I just have one last suggestion, please see my comment here: https://github.com/hubmapconsortium/hra-ui/pull/484#issuecomment-2197217702

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/39d2913f-e45a-4128-a3a6-25ce296e6b0a)

**Comment by edlu77** [comment]
Updated in develop
