### ISSUE TITLE
Landing page: Cosmetic & responsive design updates

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#472]
The HRA Dashboards landing page has been adjusted to be more dynamic and cosmetic.

This is a low priority development request. 

Please see my [annotated image](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=2933-13249&t=wzQr96lzQZxOZmiu-4) of the updates and [new section of the MVP1 canvas](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=2923-23491&t=wzQr96lzQZxOZmiu-4) for all adjustments/breakpoints:

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/6dd5827c-6e86-47ac-a22a-b8a54499519e)

**Comment by bhushankhope** [comment]
@LibbyUX fixed in PR #477 . Thanks

**Comment by bherr2** [comment]
@LibbyUX can you review and close if finished?

**Comment by LibbyUX** [comment]
@bherr2 yes, thank you for the reminder ping!

Off the top, it does need to be closer to spec:
- Currently, the font on the visual cards does not match the spec. The live production cards use Nunito Sans, however, this was specified using our Label font, Metropolis 500/Medium.
- Diversity & Inclusion needs to be reordered still in navigation

Let me review this more thoroughly tomorrow morning. I think the footers may need to match the design system footer as well. Adding to my task sheet. Thank you so much!

**Comment by bherr2** [comment]
@LibbyUX please review from this URL for now https://cdn.humanatlas.io/ui/dashboard-ui/

**Comment by LibbyUX** [comment]
[Compared with notes](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3005-7252&t=iU7XFYO84B1HLNgh-4). This is looking so fabulous!
- [Display font & overall notes](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3005-8060&t=iU7XFYO84B1HLNgh-4)
- [Visual cards](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3005-7308&t=iU7XFYO84B1HLNgh-4): Questions & Requests
- [Footer](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3005-8048&t=iU7XFYO84B1HLNgh-4): Requests

Also, two super exciting notes to document in GitHub as well as the Figma canvas:
- The Display font weight in this preview looks AMAZING. This production font weight be applied globally to all interfaces using it.
- The footer is so close. After these updates, it too can be applied globally.

Thank you! Go team!!

![Screenshot 2024-06-27 at 10 35 38 AM](https://github.com/hubmapconsortium/hra-ui/assets/97060856/2a174156-03d0-480b-8d02-0655849eb73a)

**Comment by LibbyUX** [comment]
Hi @axdanbol, wanted to provide a status update on this one:

We can close this one out when the visual cards match the [spec](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=3953-16131&t=Ipmag1HmKCUT36Xq-4).

I'm looking for:
- The specified interaction states
- The bottom of the card has a white container for the label space
- The alignment text alignment is left center
- There is no wrapping of the text when the components resize

Please let me know if there is anything else I can do for this! Thanks so much!

<img width="1177" alt="Screenshot 2024-07-11 at 3 32 19 PM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/ea959195-fbea-438b-814e-20b6175e90ae">

<img width="1619" alt="Screenshot 2024-07-11 at 3 37 04 PM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/604ebf80-3109-43b3-985c-f4c66c592cdc">

**Comment by bhushankhope** [comment]
@LibbyUX I fixed the styles for the card. Please review [here](https://github.com/hubmapconsortium/hra-ui/pull/551#issuecomment-2229199596)
