### ISSUE TITLE
Screen size notice received on 1536x960 display

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#476]
I visited the CDE landing page and I received a screen size notice on my Macbook Pro 16" with my 1536x960 display settings. I switched back to the default display settings of 1792x1120 and the notice went away.

Just want to check that this is the expected behavior on the dev side!

<img width="485" alt="Screenshot 2024-06-20 at 11 24 40 AM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/78d95de8-0931-40e2-827a-4c39ade5bd6f">

<img width="1536" alt="Screenshot 2024-06-20 at 11 26 59 AM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/d639ed47-2b81-4b38-8961-0a186dbaefdb">

**Comment by LibbyUX** [comment]
Quick update: I just tried to replicate it again and did not get the screen size notice, so this might be on my end. 

Please let me know if you need anything or if this is a non-issue! Thanks so much for everything!!

**Comment by edlu77** [comment]
I'm not able to replicate it either. Closing this issue unless it comes up again. 🤔

**Comment by LibbyUX** [comment]
Thanks so much, @edlu77 ! Have a fabulous weekend!
