### ISSUE TITLE
Mobile adjustment for Release Notes intro/date header

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#479]
I visited our release notes on my iPhone 15 Pro Max. Is it possible to move the date to the next line below when it hits a certain breakpoint? 

I iterated on our release notes section [here](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5542-19080&t=cipQAteMBiFwMI4d-4). To the left, I provide a [quick iteration](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=6050-3581&t=cipQAteMBiFwMI4d-4) about how this heading could look when it scales down. 

Let me know if you have questions or need anything else!

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/2ec10f54-b3ee-4226-9a82-e8443bd94a35)
<img width="638" alt="Screenshot 2024-06-20 at 5 56 35 PM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/64332afe-128f-431b-9a88-f6e88c197208">

**Comment by bhushankhope** [comment]
@LibbyUX fixed in PR #480
