### ISSUE TITLE
Name reveal card only needed for truncated list items

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#491]
Currently in the CDE, hovering over any cell name in the CDE vis app shows a small card of the name. 

This name card is only needed on hover when the cell name is truncated.

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/89173bbf-1cba-441c-93e9-5e70c10cc8ab)

**Comment by bherr2** [comment]
That's a little hard as the browser determines when to put in the ellipses. We'll have to look if there is a programmatic way to inspect the browser state for that. Might be harder than it looks.

**Comment by LibbyUX** [comment]
Thank you so much, @bherr2! Our dev team is amazing and so appreciated!
