### ISSUE TITLE
Sample metadata empty source data and color map links

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#492]
Both sample metadata modules were initially specified to have links out to source data and color map files.

However, this may or may not happen, after submitting #490.

Because there is no link to a dataset or color map, the text color needs to match the rest of the module.

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/77b22ec0-b4c0-43ee-b80a-e62aef5e3f8b)

**Comment by LibbyUX** [comment]
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/d058f4ca-5596-45e0-a2d2-3e2be86a8271)

**Comment by bherr2** [comment]
The sample files are on GitHub, can we just link to those and update the text here? How important is it to be on Google Sheets?

**Comment by bherr2** [comment]
Ok. It would be really helpful if you could upload the same data files that are on GitHub and provide a link for each data file so we can associate them and update where appropriate.

**Comment by LibbyUX** [comment]
@bherr2 perfect, will do! I will follow up here shortly with new specs!

**Comment by LibbyUX** [comment]
Closing this as duplicate and will follow up moving forward on #490
