### ISSUE TITLE
Add SenNet Data Portal to landing carousel & global nav header

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/hra-ui#494]
Will need to get a screenshot and some text and then add to carousel

**Comment by LibbyUX** [comment]
@bherr2 I can spearhead this one if you'd like!

**Comment by bherr2** [comment]
Yes please! Thank you

**Comment by bherr2** [comment]
Also add SenNet Data Portal (https://data.sennetconsortium.org) to the Data dropdown in the header

**Comment by LibbyUX** [comment]
Ready for dev:
- [ ] Add [SenNet Data Portal](https://data.sennetconsortium.org/) (with open in new tab functionality) to Data section in Global Nav
  - See [Figma](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=6077-3677&t=4ZT5Xt0D3lv9RbPc-4)
- [ ] Add 4th slide to 7th release carousel for [SenNet Data Portal]( https://data.sennetconsortium.org/) with open in new tab functionality
  - See [Figma ](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=6077-3713&t=4ZT5Xt0D3lv9RbPc-4)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/61b0b90d-5c41-406b-b5b9-140cbfe4b64c)

**Comment by bhushankhope** [comment]
@LibbyUX preview [here](https://github.com/hubmapconsortium/hra-ui/pull/534#issuecomment-2218385802). Please review. Thanks

**Comment by LibbyUX** [comment]
@bhushankhope looks perfect, approved! I will close this issue when it's live on the website. I appreciate you!
