### ISSUE TITLE
Replace CCFDatabase and API usage with HRA-API client

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/hra-ui#497]
- [x] Replace all usage of CCFDatabase or the CCF-API client with the HRA-API Client: https://www.npmjs.com/package/@hra-api/ng-client
- [x] Find what is still needed from the ccf-database and work with Bruce to either save that function elsewhere or find an equivalent function via the HRA-API.

**Comment by axdanbol** [comment]
Functions still in use:
- `getProbingSphereScene`
- `getOriginScene`
- `getTissueBlockScene`

Remaining TODOs:
- [ ] Refactor code to use interfaces from `@hra-api/client` instead of `ccf-database`

**Comment by bherr2** [comment]
Feel free to move those three functions to another dedicated library or possibly in the apps that use them. May be best to put it into a library.
