### ISSUE TITLE
Use new /v1/session-token route for custom data sources

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/hra-ui#498]
In the EUI when there are custom data sources set, use the /v1/session-token API to get a token and then give that token to db-status to start the EUI as normal. See <https://apps.humanatlas.io/api--staging/#post-/v1/session-token> for usage. This session-token route will be available in HRA-API v0.7.0 client.

**Comment by bherr2** [comment]
You'll be able to check for data-sources and filters here: https://github.com/hubmapconsortium/hra-ui/blob/main/libs/ccf-shared/src/lib/services/data-source/api-endpoint.service.ts#L108-L109 grab the token from /v1/session-token and then set the "hubmapToken" via its output.

**Comment by axdanbol** [comment]
Covered by #497
