### ISSUE TITLE
Visualization app QoL updates

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#499]
# Visualization app QoL updates
- Closing out major MVP1 work with cosmetic, responsive, and functionality updates for our new CDE!
- Please inspect all redesigned components carefully for responsive and aesthetic details! Any component appearing in the new canvas has been modified from our initial CDE.
- Redesigning this interface was extremely intentional to stay consistent and responsive, and to optimize screen space.
- Please don't hesitate to contact me with questions - I am always happy to help!!!
- Most of these updates are aesthetic/responsive, so I will highlight the UX updates needed below:

### UX updates + Figma links
- [x] Implement [new tooltip text](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2251-18072&t=9TwZbxqmg2N3cara-4) for the Cell Type module
- [x] Anchor icon: Implement a [tooltip hovercard](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2257-25191&t=9TwZbxqmg2N3cara-4) for this target point in the cell types list and legend

## Design repo resources
- [Typography Sheet](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=3739-15606&t=uNRJ0Klo3nHFxkfO-4)

## CDE design file
- Canvas: [Vis app redesign](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2203-11726&t=9TwZbxqmg2N3cara-4) 6.26.2024
- [Design changelog](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2251-18160&t=9TwZbxqmg2N3cara-4)
- [Updated components](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2251-17944&t=9TwZbxqmg2N3cara-4)
- [2D Sample](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2203-13292&t=9TwZbxqmg2N3cara-4)
- [3D Sample](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2246-23049&t=9TwZbxqmg2N3cara-4)

### Prototype previews
- [2D Sample QoL](https://www.figma.com/proto/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2203-13292&viewport=-31700%2C-1966%2C0.46&t=9TwZbxqmg2N3cara-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2203%3A13292&show-proto-sidebar=1)
- [3D Sample QoL](https://www.figma.com/proto/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2246-23049&viewport=-31700%2C-1966%2C0.46&t=9TwZbxqmg2N3cara-0&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2246%3A23049&show-proto-sidebar=1)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/cfabae76-7ae3-4d11-92f8-cce7cabf10f2)

**Comment by bhushankhope** [comment]
@LibbyUX I have updated the tooltip for cell types and anchor. I have also updated the header on the visualization page. Preview is available [here](https://github.com/hubmapconsortium/hra-ui/pull/501#issuecomment-2194769644). I will continue to work on the other parts of the visualization page.

**Comment by LibbyUX** [comment]
@bhushankhope thank you so much! The tooltip looks great for the cell type module and the anchor listing within the cell types module.

One question about the anchor tooltip, and we might need @bherr2's expertise here: there are two areas where the anchor should be but I don't see the anchor endothelial cell in the histogram legend preview for the 2D preview. Is this the dataset? Does the histogram legend not need an anchor? Is my computer/internet bugging out right now? Let me know if there's anything I can do on my end!

Regarding the header logos: My internet connection/computer might be buggy at the moment, but the header logo graphics appear more spacious than specified, perhaps? The preview itself is also moving slowly on my end, too. The text/font updates look good from my end. I might revisit the header appearance tomorrow when I'm back at the office.

Thanks for knocking out the tooltips today!

**Comment by bherr2** [comment]
@LibbyUX the anchor cell type doesn't show up in the histogram because it doesn't make sense to. The histogram is a distribution of the distances to the anchor node, thus all anchor cells are zero distance to an anchor cell (itself). To include it would highly skew the visualization and defeat the purpose.

**Comment by LibbyUX** [comment]
@bherr2 makes sense - thanks for breaking this down! I appreciate it!

**Comment by LibbyUX** [comment]
@bhushankhope @axdanbol @edlu77 

Just wanted to check the status of these updates: Things are looking good, but I'm wondering if you need anything from me on this? I need to make a CDE vis app figure for a paper this week, and it would be awesome to have the most recent design version implemented entirely in production. Let me know if I should review and provide comments or if I should hold off until you're ready. Thanks for everything!!

**Comment by axdanbol** [comment]
Status update for @LibbyUX
@edlu77 Please go over the app and take note/update changes that are still missing.
@bhushankhope is currently working on updating the histogram styles #515 

There are two changes that we will not be able to complete this week:
- Overlay scrollbars #521 
- Blurring bottom of scroll areas on overflow #523
