### ISSUE TITLE
Use DOI link route to paper on usage dashboard

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#500]
@bherr2 should we be using https://doi.org/10.1101/2024.03.27.587041 instead of https://www.biorxiv.org/content/10.1101/2024.03.27.587041v1 on the usage dashboard? Want to verify before requesting. Thank you!

<img width="497" alt="Screenshot 2024-06-27 at 9 30 30 AM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/06617061-d759-4e22-8690-19eae444bc2a">

**Comment by bherr2** [comment]
https://doi.org/10.1101/2024.03.27.587041

**Comment by bherr2** [comment]
They essentially go to the same place, but the DOI link will redirect to the latest version of the marker paper

**Comment by LibbyUX** [comment]
Perfect, thanks for confirming. I'll request issues when I see these QoL improvements!

**Comment by bhushankhope** [comment]
fixed this in [this](https://github.com/x-atlas-consortia/hra-dashboard-data/pull/5) PR. @LibbyUX

**Comment by LibbyUX** [comment]
@bhushankhope thank you!
