### ISSUE TITLE
Update HRA info email address to .iu.edu and select which email address is correct to use

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/hra-ui#508]
From this page https://github.com/x-atlas-consortia/hra-apps/tree/main/applications/ftu-explorer/, if you click on use FTU explorer and are directed to this page: https://apps.humanatlas.io/ftu-explorer/#/ in the upper right corner of the page it says "contact" and when you click on it, it opens a dialog page that lists cnscntr@indiana.edu which is different than the email address we use in the footer for all HRA pages "Contact HRA team" in portal which is infoccf@indiana.edu.

**Questions:**
1. Which email address should be used for all official email for HRA?  
   a) We have a separate email account we set up which we had agreed to use and do use in the footer across all HRA portal pages "Contact HRA team" button: infoccf@indiana.edu
  b) On FTU explorer top right "contact" goes to cnscntr@indiana.edu (this is not specific to HRA)
2. Correct whichever email address to use iu.edu rather than indiana.edu since IU is discontinuing all "indiana.edu" See https://kb.iu.edu/d/birs

**Comment by emquardokus** [comment]
The Cell Distance explorer does not have any "contact" button.

**Comment by bherr2** [comment]
We should use `infoccf@iu.edu` . I am unassigning myself and @LibbyUX  as any of our programmers can work on this. Essentially, we find all uses of an email infoccf or cnscentr and replace with `infoccf@iu.edu`.

**Comment by LibbyUX** [comment]
Hi @bherr2 & @emquardokus ,

We do have a contact button in the CDE: There is a contact option in the footer of the CDE, Dashboards, and future interfaces using this footer. We want to keep things simple here.

Let's discuss a global contact/feedback component eventually.

Thank you!

**Comment by LibbyUX** [comment]
Yes, I see! Thank you @emquardokus + @bherr2 for getting the email address squared away for consistency!

I read Ellen's second comment [here](https://github.com/hubmapconsortium/hra-ui/issues/508#issuecomment-2200643986) as a reminder of something I need to specify eventually. I have an opportunity to improve the consistency of the contact flow around our UIs. If either of you have any suggestions for this component, I would love to discuss on #387 !

**Comment by bhushankhope** [comment]
Fixed this in PR #512

**Comment by LibbyUX** [comment]
Hey @emquardokus I just sent a test email to infoccf@iu.edu - Can you confirm it was received?

**Comment by emquardokus** [comment]
@LibbyUX I did not see your message, so I sent my own directly to the infoccf@iu.edu and it made it through, so not sure---the email address is working though in general. I can try from website link.

**Comment by emquardokus** [comment]
@LibbyUX I see what's happening now.  When you click on "contact" in FTU explorer, it opens a window and it looks like you should be able to "submit" the message directly from there, but instead of it submitting it and sending, it instead opens up your mail program locally on your computer with a prefilled in email. That is NOT how this worked before when the email was set to the cns center one.  Can this be fixed please?

**Comment by LibbyUX** [comment]
Yes, I had the same experience. The modal component itself is quite buggy. This is morphing into a different issue, however.

Let's close this issue out by removing the contact button entirely from the FTU explorer. I will specify improvements in a week or two.

**Comment by LibbyUX** [comment]
Also, let me make a separate issue for that. We have a lot of high priority requests out right now so this is the best we can do.

**Comment by emquardokus** [comment]
@LibbyUX removing contact button is consistent with both the EUI and RUI tools.  The ASCT+B reporter has a contact button at the bottom of it's tool screen, but it immediately just opens a template through your own email program rather than opening a dialog box from browser and acting like you can send your message from it.  That would be the easiest compromise?

**Comment by LibbyUX** [comment]
@emquardokus 100%. I submitted #531 for this update. I will close this as completed with the intent of updating this in July.
