### ISSUE TITLE
Found typo: attempting to fix it on my own!

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#511]
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/335efb6c-a851-4ca2-a276-cd814203d932)

**Comment by LibbyUX** [comment]
Yaml located: https://github.com/x-atlas-consortia/hra-dashboard-data/blob/main/data/dashboards/experimental-data.yaml

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/e1247266-cdea-4268-99c2-624f862a5a7c)

**Comment by bherr2** [comment]
Congrats, was just going to send that to you lol

**Comment by bherr2** [comment]
I went ahead and updated / fixed it straight to main.
