### ISSUE TITLE
Statistics section improvements

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#514]
# Statistics section improvements
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/a3bad358-a70f-40e3-9f2b-c978411954cf)

Dashboard statistics sections are cosmetically optimized with improved responsive logic:
- Note the max width for the entire page content ([dashboards box](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3019-13331&t=BUZOcljrrossI5Sg-4)) in this design
- All linked stats sections respond as they should for all breakpoints
  - [Data](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3044-9203&t=BUZOcljrrossI5Sg-4)
  - [Usage](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3055-11476&t=BUZOcljrrossI5Sg-4)
  - [Publications](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3055-11611&t=BUZOcljrrossI5Sg-4)
  - [Experimental Data](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3055-12158&t=BUZOcljrrossI5Sg-4)
  - [Diversity & Inclusion](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3055-12233&t=BUZOcljrrossI5Sg-4): Note that this one looks slightly wonky but it was the best I could do for all breakpoints. Reach out with suggestions if you have them!

## Figma Resources
- [Statistics Section Components + Dev Notes in the Canvas](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3060-14155&t=BUZOcljrrossI5Sg-4)
- [Title Component](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=2260-4621&t=BUZOcljrrossI5Sg-4)
- [Statistics Card](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3041-26377&t=BUZOcljrrossI5Sg-4)
- [Stats Container](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3060-14194&t=BUZOcljrrossI5Sg-4)
- [Tooltip](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3060-14191&t=BUZOcljrrossI5Sg-4)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/bfbf4010-a948-4729-b481-6878596609c1)

**Comment by bhushankhope** [comment]
Fixed this in PR #530
