### ISSUE TITLE
Vega-lite visualization initial style sheet

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#515]
TO DO: Specify Vega-lite visualization style sheet & guidance for development in the Design System Repository's Pattern Library.

### Resources
- [Vega-lite Overview](https://vega.github.io/vega-lite/docs/)

**Comment by LibbyUX** [comment]
@axdanbol, please see my Vega-lite Pattern sheet. Let me know if you need anything else in here! These updates are now ready for development.

Team, please note that some of these updates may be iterative, as I need to see what this looks like in the visualizations.

### Design System Repo
- Figma: [Vega-lite Patterns](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=4563-25025&t=lGRUz8NDqzwwbF8s-4)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/05dd6435-383f-44d5-a085-f6a424cfd279)

**Comment by LibbyUX** [comment]
I added casing notes from Katy & my Slack messages this morning. The [Vega Pattern sheet ](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=4563-25025&t=3yTkV0MY1LkgR0Ln-4) has been updated.

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/ea0a9551-6d2f-4837-a1b3-b8bda3b21d4a)

**Comment by bhushankhope** [comment]
@LibbyUX I have updated the font styles for the visualizations according to the spec for both CDE and Dashboards. But I see that some of the labels/legend is being cut when we rotate the labels by 45 deg. Latest preview is [here](https://cdn.humanatlas.io/ui--staging/dashboard-ui/)

**Comment by LibbyUX** [comment]
@bhushankhope thank you for working on this! We're moving in the right direction! I have reviewed both UIs, thank you for getting this started!

### Rotation
When I rotate 45 degrees in Figma, this is what I see in Figma vs in production:
<img width="813" alt="Screenshot 2024-07-11 at 3 16 08 PM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/6d5e265e-23d3-478c-aa31-865e171d1633">

<img width="525" alt="Screenshot 2024-07-11 at 3 17 59 PM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/4927c6d3-5cc9-4f38-aad1-102fe673d97e">


### Cut off labels
Can we try making all Vega-lite visualizations a 3:1 ratio with longer, responsive containers? We're going to have to keep iterating what looks best but is also readable/interactive.

Can you try these layouts the Vega-lite visualization pages?
- [Data](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3007-12263&t=IlxNDq8dKpH7m2dm-4)
- [Usage](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3051-11169&t=IlxNDq8dKpH7m2dm-4)
- [Experimental Data](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3055-11894&t=IlxNDq8dKpH7m2dm-4)

### Dashboards/Vega font styles
Can we get closer to the [Vega Style Sheet - Font Specs](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=4569-963&t=Ipmag1HmKCUT36Xq-4) in Dashboards? I'm seeing non-Metropolis fonts, light appearing font weights, and letter casing opportunities:
 
<img width="1332" alt="Screenshot 2024-07-11 at 3 25 07 PM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/73021812-d57d-4c41-b66a-961d3161ae8c">

**Comment by LibbyUX** [comment]
Hey @bhushankhope I just found a feature request from Katy, so I added a [number separator section](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=4569-953&t=TiIT6Mk7ZEzbjhou-4) to the Vega-lite Style Sheet!

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/e97e8eeb-09ce-48d4-a6da-a48204f785ed)
<img width="675" alt="Screenshot 2024-07-11 at 3 54 04 PM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/f06b13de-451d-4fd6-af77-6a3917239545">

**Comment by axdanbol** [comment]
@bhushankhope
- See https://vega.github.io/vega-lite/docs/config.html#format and https://d3js.org/d3-format#locale_format for number formatting
- For letter casing titles, labels, etc. we might have to add data transforms/expressions
- Try using negative angles to rotate in the other direction (don't rotate short labels that already fit)
- Definitely try using 3:1 ratio layout

**Comment by bhushankhope** [comment]
@LibbyUX I have modified the font styles and the angle for the labels
[Preview](https://cdn.humanatlas.io/ui--staging/dashboard-ui/)
I am yet to fix the padding/spacing issues in the charts

**Comment by bhushankhope** [comment]
@LibbyUX all the latest changes can be reviewed [here](https://cdn.humanatlas.io/ui--staging/dashboard-ui/)
