### ISSUE TITLE
CCF ontology page content updates

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#516]
Content being added here: https://docs.google.com/document/d/1QbI8faNtItzWa_qTIuvxTTO5R__HB6GEiCrRv_hpkDo/edit#heading=h.fza1upw437vc

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/ddbbe7d6-af9f-4641-96ec-d82ba8afedca)

**Comment by LibbyUX** [comment]
Status update: 

I just spoke with @andreasbueckle about this content: We will wait until @bherr2 is back to finalize.

Thank you for the help on this one today, @bhushankhope & @andreasbueckle!

**Comment by LibbyUX** [comment]
@bherr2, can you please take a look at the questions in [this document](https://docs.google.com/document/d/1QbI8faNtItzWa_qTIuvxTTO5R__HB6GEiCrRv_hpkDo/edit#heading=h.fza1upw437vc), add what is needed, and resolve the comments? Thank you!

**Comment by LibbyUX** [comment]
Also, @bherr2 this is the type of content I was thinking for a blog post in a news/updates section of the new HRA. I understand where you are coming from that a traditional blog is generally updated often. We get requests to make new pages often enough that I believe blogging functionality makes sense. It can be updated as little or frequently as needed for news-related updates in this area. Then, the content is timestamped, so it doesn't just look like a forgotten webpage.

I detail my thoughts in depth in #446 & in [my humanatlas.io Figjam canvas](https://www.figma.com/board/H3CK8StFdAphCFtFAHAwhM/Information-Architecture?node-id=790-2366&t=soPWbyB10xBaClas-4) regarding this functionality for best content strategy UX. Eventually, this could be a major user experience improvement and internal workflow improvement for everyone.

**Comment by LibbyUX** [comment]
# Content ready for dev
New CFF Ontology ready for dev. Please use the [CCF Ontology Google Doc](https://docs.google.com/document/d/1QbI8faNtItzWa_qTIuvxTTO5R__HB6GEiCrRv_hpkDo/edit) as the source of truth for this content and format as similarly as possible. Replace all current CCF Ontology text and image content with this text content.

<img width="543" alt="Screenshot 2024-08-01 at 10 24 17 AM" src="https://github.com/user-attachments/assets/6ee4406e-a4a9-4ae0-9ae0-abadbdd76866">

**Comment by andreasbueckle** [comment]
@bhushankhope 
Below are my responses to your 3 questions:

### Cards
These cards are (more or less) relevant to the CCF Ontology. I would keep them.

### URLs
I would leave them separate from the text so readers understand what they are clicking on.

### References:
Please add `doi: https://doi.org/xxxxxxxx`, like:

1.	Herr, B. W. et al. Specimen, biological structure, and spatial ontologies in support of a Human Reference Atlas. Sci. Data 10, 171 (2023). doi: [https://doi.org/10.1038/s41597-023-01993-8](https://doi.org/10.1038/s41597-023-01993-8)
2.	Börner, K. et al. Tissue registration and exploration user interfaces in support of a human reference atlas. Commun. Biol. 5, 1369 (2022). doi: [https://doi.org/10.1038/s42003-022-03644-x](https://doi.org/10.1038/s42003-022-03644-x)

**Comment by bhushankhope** [comment]
@andreasbueckle  thank you

**Comment by bhushankhope** [comment]
@LibbyUX this is merged into main. I am closing the issue. Thanks
