### ISSUE TITLE
Usage visualization improvements

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#519]
# Usage visualization improvements

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/d34342d9-ad6e-4f9f-ad0a-b34ad412ac36)

Two visualizations need to be restructured to provide a better visualization user experience in the [Usage Dashboard](https://apps.humanatlas.io/dashboard/usage):
- Digital Object Usage
- HRA Products Usage

Please see the communication from Katy for guidance:

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/1f0d915c-20f7-4dff-abb0-c33fc3415a96)
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/b8edde3b-3163-4e4e-a469-ed3ec31d24f6)

Mentioning @bherr2 & @axdanbol - Please let me know if there is anything I can do to support. Thank you!

**Comment by bherr2** [comment]
![image](https://github.com/hubmapconsortium/hra-ui/assets/34098595/ed78eeaa-00ce-4293-bb4f-55a5d7c0f59a)

:-D

**Comment by LibbyUX** [comment]
@bherr2 LIGHT SPEED FIXES! You rock!

**Comment by bherr2** [comment]
PS made one more improvement :-)

![image](https://github.com/hubmapconsortium/hra-ui/assets/34098595/2d8afec3-a87f-4a54-b5c1-9f29a6880da9)
