### ISSUE TITLE
Download Data button

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#520]
# Download Data button:
Mentioning @bherr2 for a feasibility check on this question:
- The Download Data button does nothing on click in Google Chrome
  - This button is useless unless we have data for users to download
- Can we hide it when we don't have shareable data for certain FTUs?

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/43095230-bb86-40ed-a09d-99ca996d3fc2)

**Comment by bherr2** [comment]
Probably best to hide completely for now, but that is a possibility once we can finally get data in systematically.

**Comment by LibbyUX** [comment]
That sounds great to me, thanks @bherr2. This is ready to be hidden if we don't have downloads! Let's revisit this later as we scale up this application.
