### ISSUE TITLE
Overlay-Scrollbar

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#521]
# New component for all apps: Scrollbar appearing on hover
@axdanbol and I caught up yesterday on scrollbars. In the spirit of improving the density of our interfaces, I have an ask for development: Can we please implement a scrollbar that appears on hover of certain modules/containers? This is only for certain containers, not the overall scrollbar of the web page.

This component would work wonders instantly in FTU Explorer components (FTU Library, Matrix Component, and Source Data Section) and Cell Distance Explorer components (Cell Type list & Histogram Legend).

Eventually, we will need this component for the EUI, RUI, the new Digital Object Database in the HRA Portal, and ASCT+B Reporter. There's probably more UIs that will need this, too!

This component pattern is intuitive, clean, and it maximizes what we can show in our UIs.

You can see this functionality in several web browser apps, like Slack and Figma.

![FD47B1AC-3FE2-4FB2-8302-E211146F8E6F](https://github.com/hubmapconsortium/hra-ui/assets/97060856/bdac0da9-d738-44b7-a0cf-10abd234a1d6)

## Figma

I have specified this [scrollbar](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=4432-29127&t=3yTkV0MY1LkgR0Ln-4) in the Design System Repo. It has two variants, 12px & 8px. 

This design has been implemented in components in the redesigned CDE ([Cell Types list](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2228-16952&t=oDGeXCPTqaPIVvjk-4) & [Histogram legend](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2228-15687&t=oDGeXCPTqaPIVvjk-4)).

**Comment by axdanbol** [comment]
Investigate https://kingsora.github.io/OverlayScrollbars/ for implementing this feature

**Comment by axdanbol** [comment]
Or https://github.com/MurhafSousli/ngx-scrollbar

**Comment by LibbyUX** [comment]
@axdanbol - Thanks so much for everything on this! Let me know if there's a better name for either of these atoms!

### File: Design System Component
- [Overlay-Fade](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Design-System-Components?node-id=214-1697)
- [Overlay-Scrollbar](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Design-System-Components?node-id=214-1253)

### File: Design System Repository
- [Overlay-Fade](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=5134-20955&t=KU9AEHXezZo41JCf-4)
- [Overlay-Scrollbar](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=5134-20962&t=KU9AEHXezZo41JCf-4)
