### ISSUE TITLE
Use Lightweight Atlas Components - Medical Illustration Viewer : Hover not working

### ISSUE THREAD

**Issue by supriyabidanta** [hubmapconsortium/hra-ui#526]
FTU Explorer > Medical Illustration Viewer component is not working. 
When you click on "use app" button, it opens the component but the the side scroll bar is disappears when you hover over any of the the illustration.

https://github.com/hubmapconsortium/hra-ui/assets/117299113/52a4f796-5284-44f2-88ac-5a1948bcaab6

**Comment by axdanbol** [comment]
@supriyabidanta I have pushed a fix and verified that it works on my computer. Could you please double check that it works on your computer as well before we close this issue?

**Comment by axdanbol** [comment]
@supriyabidanta There is not supposed to be a sidebar but it should show tooltips when hovering over cells
