### ISSUE TITLE
Add Cell Type Annotations page to navigation, data overview, and website

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#535]
A new page has been requested: Cell Type Annotations. I am working to make updates in Figma now. I will remove the designers label and I will relabel this as "product team: developers" when ready for development!
- Google Doc: [Cell Type Annotations page content](https://docs.google.com/document/d/15OtSKlQQsQ8tsB62_egzjjN3BqCjefCxgIGvBUoGGvA/edit)
- Figma: [Cell Type Annotations canvas](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=6107-4482&t=KJpij81pFMif3bB3-4)

**Comment by LibbyUX** [comment]
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/96f0f475-8310-4d61-95f1-ecb6f8e10fef)


# Ready for dev
- [ ] Add [Cell Types Annotations page](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=6109-25958&t=KJpij81pFMif3bB3-4) to the website.
  - **Dev note:** Content of this nature will not be in place on the redesigned HRA website, so please create a plain text, simple table. Ideally, we do use our Inter table fonts, but I won't be mad if we have to cut corners in favor of other projects right now. Do let me know if you have questions or need any help!
  - **Side note:** Hi, @emquardokus! Did you provide this data? If you did provide, can you please also provide a spreadsheet, or Github link to this data, so we don't have to manually enter this data from the [Google Doc](https://docs.google.com/document/d/15OtSKlQQsQ8tsB62_egzjjN3BqCjefCxgIGvBUoGGvA/edit#heading=h.fza1upw437vc)?
- [ ] Add [Cell Type Annotations](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=6077-3682&t=KJpij81pFMif3bB3-4) to the Data section of the navigation menu
- [ ] Add [Cell Type Annotations button card to the Data Overview page](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=6109-25913&t=KJpij81pFMif3bB3-4)

**Comment by emquardokus** [comment]
@LibbyUX the table comes from the same github as the original link I had that was resolved in the google doc, let me get the link to the exact table. @andreasbueckle can you supply access to table?

**Comment by andreasbueckle** [comment]
Here you go: https://github.com/x-atlas-consortia/hra-pop/blob/main/output-data/v0.10.2/reports/hra/ct-per-organ-per-tool.csv

**Comment by emquardokus** [comment]
@andreasbueckle I noticed that the table you point to doesn't look exactly the same, why is there an purl instead of an organ name? Are the numbers really the same?
<img width="891" alt="Screenshot 2024-07-10 at 9 11 27 AM" src="https://github.com/hubmapconsortium/hra-ui/assets/47257000/a2b43b0b-0c70-4369-8d18-e6c86496939e">

**Comment by andreasbueckle** [comment]
Good question. That PURL is white adipose tissue. I would keep the last column, because it helps us explain why we do not have any cell type populations for the ones with many datasets but without a reference organ.

**Comment by LibbyUX** [comment]
Hi @bhushankhope thanks for self-assigning. Some small text edits were just made, but it was text only. Additionally, I just let our content writers know that the doc is frozen and to submit any issues separately via GitHub issues in this repo.

Noting the small changes here:
![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/1ca92884-2945-408f-9256-90518e4766ac)

**Comment by bhushankhope** [comment]
@LibbyUX please review the new page [here](https://github.com/hubmapconsortium/hra-ui/pull/539#issuecomment-2220936701)

**Comment by LibbyUX** [comment]
Thank you @bhushankhope !
