### ISSUE TITLE
Dashboard overview updates

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#537]
# Ready for dev
I sourced DOI links for all Read Paper buttons in our Dashboards. 
- [x] Can you please update all buttons to the specified routes in [Figma](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3019-13294&t=5tmYEzVn1dCy5OVS-4)?

I added max widths for all overview sections
- [x] Add 1012px max width for overview sections

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/7413e0eb-877b-4811-a16b-de5e8269637e)

**Comment by LibbyUX** [comment]
This is related to #502

**Comment by bhushankhope** [comment]
@LibbyUX publication and Diversity and Inclusion URL is same. Is this correct?

**Comment by LibbyUX** [comment]
Good looking out @bhushankhope. Yes, they should be the same URL, however, I used an outdated DOI.

Both Diversity & Pubs need to link to this DOI: https://www.nature.com/articles/s41597-024-03416-8

Updating in Figma now!

**Comment by bhushankhope** [comment]
@LibbyUX both the changes are done and can be reviewed [here](https://cdn.humanatlas.io/ui--staging/dashboard-ui/)

**Comment by LibbyUX** [comment]
@bhushankhope amazing! I love that max-width on the entire content, too. This is approved. I will close when these are live. Thank you so much!
