### ISSUE TITLE
Navigation header: Route to humanatlas.io + open in new tab

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#544]
I know we have the EUI elsewhere as a customizable component, so I want to verify this request won't break anything:

Is it possible to repurpose this route to open in a new tab to https://humanatlas.io/ instead of apps.humanatlas.io/eui ?

Mentioning @axdanbol for visibility! Thank you so much!

<img width="614" alt="Screenshot 2024-07-11 at 8 31 01 AM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/d74a07b8-bdac-4946-814d-90a07a988ead">

## Relevant communication

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/e8ca73c0-8842-46d2-917c-faaf5c420ab7)

**Comment by LibbyUX** [comment]
@bherr2 @edlu77 @axdanbol 

Hey team, I hard refreshed my browser and I'm still getting apps.humanatlas.io/eui instead of humanatlas.io in a new tab when I click the HRA Registration header in the EUI.

I'm knocking out loose ends before vacation and I have an email pinned from Katy for this feature request. 

Please let me know if there's anything I can do to help on this!

<img width="429" alt="Screenshot 2024-08-01 at 10 30 28 AM" src="https://github.com/user-attachments/assets/233db366-5981-43b2-b0e9-46ccafde9b51">

**Comment by axdanbol** [comment]
@LibbyUX This should now be fixed as soon as the deployment has finished. I'll close this issue when I have verified that it works :)
