### ISSUE TITLE
Create vis app cosmetic & responsive updates

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#556]
# Create vis app cosmetic & responsive updates

Welcome to the conclusion of our CDE QoL updates for this summer! The create vis app has been redesigned for simplicity, responsiveness, and longevity.

<img width="929" alt="Screenshot 2024-07-16 at 12 48 17 PM" src="https://github.com/user-attachments/assets/ab6258d4-a00e-4df2-bfed-3c38f7bef674">

<img width="1325" alt="Screenshot 2024-07-16 at 12 51 32 PM" src="https://github.com/user-attachments/assets/18eabf78-a30d-4db1-98e4-e0e67e41077b">

### Spec matching to production
- I would love to get the background as close to spec as possible
  - The content is intentionally off center for aesthetics: We want to see @u-p-design's amazing illustration on larger breakpoints!
- Please note the states on all buttons, selects, and inputs

### Design updates
- The UX copy/text has been simplified to keep this process super straightforward for users
- All fonts and button component sizes have been optimized for cosmetic purposes
- Min/max widths added on content container, individual modules, tooltips, and segmented button in step 4
- Use Google Sheet links for templates
  - Cell Type Table Template
  - Color Map Template
  
### Figma
- [Responsive Vis App](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2513-31387&t=2yD6q8HGsh7qv1yT-11)
- Component: [Creation modules](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2513-30289&t=2yD6q8HGsh7qv1yT-4)
- [Creation tooltips](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2513-30415&t=2yD6q8HGsh7qv1yT-4)

### Background details
- [Background styles section](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2513-31383&t=2yD6q8HGsh7qv1yT-4)
`background: var(--cell-image-bg, linear-gradient(0deg, rgba(252, 252, 252, 0.16) 0%, rgba(252, 252, 252, 0.16) 100%), url(<path-to-image>) lightgray 50% / cover no-repeat, #FFF);`

<img width="573" alt="Screenshot 2024-07-16 at 12 32 34 PM" src="https://github.com/user-attachments/assets/a8207877-8d2b-4103-941f-923bda8e3eeb">

**Comment by LibbyUX** [comment]
@J-Yash - quick question:

Currently on the production version of the Create Vis app (https://apps.humanatlas.io/cde/create) we are linking to data template on GitHub, though we should be linking to this data in Google Sheets for the best user experience:
- [Cell Type Table Template](https://github.com/hubmapconsortium/hra-ui/blob/cell-distance-explorer/apps/cde-ui/example-data/nodes.csv)
- [Color Map Template](https://github.com/hubmapconsortium/hra-ui/blob/cell-distance-explorer/apps/cde-ui/example-data/color_map.csv)

We also have different resources on Google Drive that were uploaded in April:
- [Cell Type Table Template](https://docs.google.com/spreadsheets/d/1gfwoS3x_7wHKRLAIpzJ_ROqotXy2LMrLfyD_l-QSyoI/edit?gid=0#gid=0)
- [Color Map Template](https://docs.google.com/spreadsheets/d/1a26YakjfrMWCdZgEOdX7OTQUycAfUSl-P7TBHV4j4lg/edit?gid=0#gid=0)

Which version displays the ideal data for these templates? If it's the GitHub version, I will upload in Drive and delete your versions from April. Please let me know! Thanks for your help!

**Comment by J-Yash** [comment]
@LibbyUX for the templates on `/create`, you can go ahead and use the GitHub versions. Feel free to replace the ones in Drive with the ones on GitHub.

**Comment by LibbyUX** [comment]
@axdanbol + @edlu77 - one last small request on this one.

Can y'all please update the template button routes (+ open in new) to the following:
- [Step 1's Template](https://docs.google.com/spreadsheets/d/1EUf7CUZb0NprgxBeX3nS3GXyUM89edIRH6NSeUsR3nY/edit?gid=47698780#gid=47698780)
- [Step 4's Template](https://docs.google.com/spreadsheets/d/1sjaGTCs3J9CjrkowxkyJrIfHk64w_nDyYrgprbMbdqE/edit?gid=0#gid=0)
