### ISSUE TITLE
Metadata Issue: Update Metadata for Intestine 2D Example

### ISSUE THREAD

**Issue by J-Yash** [hubmapconsortium/hra-ui#558]
Based on the data provider's input, please make the following changes to the `Sample Metadata` card (image below) for 2d Intestine Sample (https://apps.humanatlas.io/cde/example/0):

* Change `Technology` from `CODEX` to `CyCIF`
* Change `Source Data` from `2D Intestine Sample` to `2D Large Intestine Sample`
* Change `Organ` from `Intestine` to `Large Intestine`

![image](https://github.com/user-attachments/assets/27149f15-5e59-400c-ac54-367b01e857d2)

**Comment by bhushankhope** [comment]
@J-Yash @LibbyUX updated the metadata [here](https://github.com/hubmapconsortium/hra-ui/pull/559#issuecomment-2231671893) . Please verify. Thanks

**Comment by J-Yash** [comment]
@bhushankhope I reviewed. Looks good. Feel free to close the issue. Thanks!
