### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#562]
# Button: Navigation
To do: Please add our call-to-action button to Storybook
- Figma: [Design System Components - Button: Navigation](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Design-System-Components?node-id=13-1245)

### Label
Use for navigation category category labels.
### Item
Used for single-standing navigation items or navigation items that fit within a category.
## Size variations
- Large
- Medium
## Component states 
- Ready/default
- Hover
- Active/pressed
- Focus
- Focus Visible
## Behavior
- Focus state overrides hover. Active/pressed overrides focus.

![image](https://github.com/user-attachments/assets/72b33914-ef3f-4e5d-a9b5-04e9ce5f2c64)

**Comment by LibbyUX** [comment]
# Ready for dev
- [Design System Component: Button](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Design-System-Components?node-id=5-842)
- Always use primary variants first if hierarchy is present
- Please see my usage notes and all variants in the Button component in the [Design System Repository](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=1710-7&t=d92X1kGQL5bAfqmN-4):

![image](https://github.com/user-attachments/assets/2a91f4d0-25a5-4cc3-948d-667a7ff85e3f)

**Comment by bhushankhope** [comment]
@LibbyUX please review the buttons [here](https://github.com/hubmapconsortium/hra-ui/pull/658#issuecomment-2299597337)
Thanks.

**Comment by LibbyUX** [comment]
# Design System update
I am working to better unify our styles with Material 3 design standards.

### Delete variants:
- Nav item (underlined)
- Flat round, primary and secondary
- Flat CTA medium sized variant, primary and secondary

### Add:
- Basic primary: [icon variant](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Explorer-Design-System-Repository?node-id=5902-27005&t=OLeMjSiIQV6Zn1Bz-4)
- [Ripple effect](https://material.angular.io/components/ripple/examples) to all buttons besides disabled states, if possible
- Disabled state buttons: Is it possible to always have a micro tooltip on hover or focus of disabled buttons? It could be helpful to let the user know why something is disabled.

### Update: Flat CTA
I removed all size variants to make this easier for widespread usage. The "large" variant was most used and it has been updated:
- Update: 14px/medium label size
- Update: Space between label and arrow icon (4px previously, 6px now)
- Add: Drop shadow to CTA primary button hover state
- Add: Disabled state CTA

### Update: Basic
- Add: Icon variant to primary set
- Add: Disabled state
- Update: Largest font size to 14px/medium, removing large variant
- Update: Hover state color
- Update: Pressed state color

Update: Button Toggle
- Update: Color states for hovered, pressed, and selected

![image](https://github.com/user-attachments/assets/dc8872b9-f69e-45e7-9bd1-dc2056522a4f)

![image](https://github.com/user-attachments/assets/d7af5409-fc36-4c3a-a3d8-9ab84f8db262)

**Comment by bhushankhope** [comment]
@LibbyUX I have made the css changes to support new design. Please review [here](https://github.com/hubmapconsortium/hra-ui/pull/698#issuecomment-2334382820). Thank you
