### ISSUE TITLE
Bug(ccf-rui): Organ input should accept an iri

### ISSUE THREAD

**Issue by axdanbol** [hubmapconsortium/hra-ui#569]
### Expected
It should be possible to pass an iri as the organ, ex:
- http://purl.org/ccf/latest/ccf.owl#VHFRightPalatineTonsil
- https://purl.humanatlas.io/ref-organ/palatine-tonsil-female-right/v1.1#primary

### Actual
No organ is selected

### Cause
The comparison between the entity label and organ name in [reference-data.state.ts:181](https://github.com/hubmapconsortium/hra-ui/blob/main/apps/ccf-rui/src/app/core/store/reference-data/reference-data.state.ts#L167) is case sensitive preventing the correct organ from matching.

**Comment by bherr2** [comment]
We already have support for them selecting by ontologyId (the uberon term for kidney for instance) plus sex and side. Doesn't that still work? See https://github.com/hubmapconsortium/hra-ui/blob/develop/apps/ccf-rui/src/app/core/store/model/model.state.ts#L531 . If it doesn't work, we need to fix it.

I'm hesitant to have people set the reference organ IRIs as they change fairly frequently and would require them to use string manipulation to create if they were trying to change sex / side. One case where it might make sense is when editing existing registrations, BUT the RUI should automatically switch to the right organ anyway (if not, that's a bug).
