### ISSUE TITLE
Tooltip Card

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#577]
# Tooltip Card
Please add our tooltip card to our HRA Design System Storybook.

![image](https://github.com/user-attachments/assets/3e2e2de4-c76e-4241-a125-c8600a61fc69)

## Styling Specifications
- Variants
  - Medium with Label Medium font
  - Large with Label Large font
  - Variants with and without sections
- Section title color: HRA Blue #201E3D 
- Body color: Gray 2 #4C4C58
- Drop shadow/box shadow
- 8 degree corner radius

## Behavior
- Activates on hover of a hover target:
  - Info icon: Mat-Icon-Button
  - CDE's Anchor Icon
- Future versions notes: Additional variants will likely be added in future iterations. We may need clickable functionality to display screenshots and buttons to dismiss the tooltip.

## Usage
- Used to provide additional context about a feature to condense our UIs.
### Current UIs with this feature
- Cell Distance Explorer
- Dashboards
### UIs that will eventually use this component
- FTU Explorer
- EUI
- RUI
- ASCT+B Reporter
- HRA Portal
- & likely more

## Component
- Design System Component: [Card: Tooltip](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Design-System-Components?node-id=52-100)

**Comment by bhushankhope** [comment]
@LibbyUX here is the preview [link](https://github.com/hubmapconsortium/hra-ui/pull/585#issuecomment-2251279629) for the tooltip in the design system
