### ISSUE TITLE
Create Vis App MVP2

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#579]
Feature request from @katyb converted into a GitHub issue:

![image](https://github.com/user-attachments/assets/d5e7050f-dd74-4a72-a923-817ee42ad2d3)

**Comment by bherr2** [comment]
There is no header for edges for various reasons. We can do this in the next MVP once it's spec'ed, but cannot change it now as it will break a lot of stuff. We were going to add more flexibility to headers in the next MVP, so would be appropriate then.

**Comment by LibbyUX** [comment]
Thank you @bherr2 !

**Comment by LibbyUX** [comment]
@bherr2 - Regarding this UI: Does this need to be a table that users can edit within the CDE? If so, would a modal/overlay with a table to edit serve this feature request? Do you have any other ideas for this specific feature request that I should take into account?

**Comment by bherr2** [comment]
No, they cannot edit the data from CDE

**Comment by LibbyUX** [comment]
@bherr2 thank you! Does this feature need a front-facing UI? If so, do you have any expectations or technical limitations that I should be aware of during the design process?

**Comment by bherr2** [comment]
Yes, for the input data, we will need a user interface for them to change/verify the column headers (thus flexibility in the headers). That way if they have MY_X_VALUE they can say that is for x, and MY_TERM_VALUE_ERERERDFDF is actually the cell type column, etc. We will try to choose the right one by default, but they will need to be able to tweak it, like we do with the anchor cell type feature.

**Comment by LibbyUX** [comment]
Ok great, thank you @bherr2! So, to me, this seems to be a user interface modification within the Create Visualization Application - Is this correct?

If so, please see our most recent iteration of the CDE's [Create Vis App](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2471-18515&t=LPpH61BiHxgBrHtz-4).
- Could this be a UI within Step 1 that appears after they upload their data?
- Or would it be better placed elsewhere?

![image](https://github.com/user-attachments/assets/dd18cfc6-1856-480d-91cc-9ccc8d0c25a7)

**Comment by bherr2** [comment]
Yes, it would need to be part of step 1

**Comment by LibbyUX** [comment]
@bherr2 Great. I'm on this now. I will follow up here with more questions as I have them. Thanks for all of your help!

**Comment by LibbyUX** [comment]
@bherr2 - I broke this feature request out from the first step of uploading data. Initially, we were using "Format and upload data" as the Step 1 title. Adding this step is formatting/organizing, in a way. 

Compare the [previous design](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2665-8121&t=mXmyi4TKZNBFDEPx-4) (from mid-July) to the [8.1.2024 iteration](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2652-25287&t=mXmyi4TKZNBFDEPx-4) accommodating this feature request.

Please comment in Figma directly if I missed anything or if any other ideas pop up that you need me to track.

![image](https://github.com/user-attachments/assets/918fc4a0-5689-4276-b408-1b82dcd4b063)

**Comment by bherr2** [comment]
One immediate thing, is that we would want to pre-select the required columns if we can determine it from the header. In which case, if we pre-select, they won't see the dropdown label you have, so you'd need to make it more obvious what the selected things were.

**Comment by bherr2** [comment]
We _do not_ want them to have to select the right columns every time, especially if they follow our preferred csv header template

**Comment by LibbyUX** [comment]
Thank you for the feedback @bherr2 - This is their first impression of the page without uploading anything.

I want to make sure I'm tracking correctly: Say they complete step 1 and upload a perfectly formatted cell type table CSV. Once uploaded, in step 2, the mat-selects update to the modified inactive state because of their well-formatted data with our preselection behavior. Is this accurate? Or do you envision this differently? Is there anything majorly wrong with this workflow?

I will iterate more late next week!

![image](https://github.com/user-attachments/assets/efb74176-496a-4090-9b85-9d005560d159)

**Comment by bherr2** [comment]
Yes, something like you show would work! I assume "Form field selection" would actually be "x", "y", "Cell Type" respectively for the required columns if they uploaded in the preferred format.

**Comment by LibbyUX** [comment]
Great! 

Yes, that's correct, the [select components](https://material.angular.io/components/select/overview) return a preselected header name based on their data. Will we need an error state for these selects?

Currently, I think some verbiage updates can happen to make this workflow easier, but good to know I'm on the right track.

**Comment by bherr2** [comment]
We should probably do sanity checks on the values (ie make sure x and y coordinates are actual numbers) in which case an error could appear. And of course, they can't proceed until they've chosen the required columns.

**Comment by LibbyUX** [comment]
![image](https://github.com/user-attachments/assets/5bd8cae9-650d-45a3-a261-1c743da8fcb1)


# Create Vis App MVP2
Several new cosmetic and functional updates to this page. Please ask if you have questions!
- NEW: [Creation Modules](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=3099-14686&t=TNPV3og4jZMA4eMq-4)
- Page: Entry/ready state
- Page: Modified & ready to generate vis

## Design Details
- Many cosmetic UI updates to improve/unify this UI with future UIs
- Tooltip text has been updated everywhere on this page

## Behavior Details
- All creation modules are a fixed width. It's too much to manage responsively at the moment.
- The Download Template buttons in step 1 & 5 need to download the template CSV file directly. Katy requests we upgrade the user experience from a Google Sheet template to downloading these files directly from the page.
- Organize Data (2) preselects columns based on their titles.
- Configure Parameters (Step 3) form fields computationally updates the visualization output.

![image](https://github.com/user-attachments/assets/dddc230c-f5d6-44fa-b1e6-c612f6d279f2)

**Comment by LibbyUX** [comment]
Lib to follow up shortly about template buttons

**Comment by LibbyUX** [comment]
Hey @edlu77! I spoke with @bherr2 & Katy just now on the template button functionality: There was a misunderstanding about updating this functionality, but we got it sorted.

We are going to use the same functionality that we currently have, linking out to the template on Google Sheets. There is no change in functionality. This said, I am going to edit/delete that bullet point in my original handoff comment and edit the button from basic text with icon to just basic text. Please don't hesitate to reach out with any questions! Thanks so much!

**Comment by edlu77** [comment]
@LibbyUX Thanks for sorting this out!

**Comment by LibbyUX** [comment]
Hi @edlu77 & @bherr2,

I have updated the workflow cards in the CDE spec per our conversation today. Please see in Figma:
- Canvas Section: [Create Vis workflow cards](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=3259-11536&t=Gb41FhnwTo1egMzf-4)

I also edited my [handoff comment](https://github.com/hubmapconsortium/hra-ui/issues/579#issuecomment-2334736581) on this issue to:
- replace verbiage on the workflow card (formerly creation modules in Figma/GitHub issues)
-  update the canvas route in Figma.

Please let me know if you have any questions! Thanks for the great meeting earlier!

**Comment by LibbyUX** [comment]
@edlu77 - Thanks for meeting with me today! Per our meeting, I created two disabled/error indicator state variants for required steps 2 & 3, before a user has uploaded a CSV file.

### CDE Figma file:
- [Step 2](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=3814-12419&t=SMX48g5zsJFw3bXX-4)
- [Step 3](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=3817-23466&t=SMX48g5zsJFw3bXX-4)

![image](https://github.com/user-attachments/assets/befdb29d-9c7a-4fc9-8754-09b8035db228)

**Comment by LibbyUX** [comment]
Thank you so much @edlu77, @axdanbol, @J-Yash, and @bherr2 for your work on this!
