### ISSUE TITLE
Brand: Logo

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#584]
<img width="1808" alt="Screenshot 2024-07-25 at 12 14 50 PM" src="https://github.com/user-attachments/assets/fbc5e04c-53a0-4374-bbb6-6eb2467332c4">

# Brand: Logo
More information will be provided on our logo in the style guide. This is information about the brandmark component.

### Figma
- [Brand: Logo](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Design-System-Components?node-id=84-802)

## Variant Usage
- Colors
  - Black: Navigation headers
  - White: Footers
- Height
  - 48px: Smallest variant used in logo button components
  - Scalable: Used in footer

**Comment by LibbyUX** [comment]
I updated and simplified this today for development with the help of @bhushankhope!

Two properties and two overall components:
- Location: nav header, footer
- Color: blue, white

![image](https://github.com/user-attachments/assets/20f67ff1-5704-449b-9b96-9b5fc1d66685)

**Comment by bhushankhope** [comment]
@LibbyUX here is the preview for the brand logo
[preview](https://github.com/hubmapconsortium/hra-ui/pull/590#issuecomment-2256603449). Please review, thanks

**Comment by LibbyUX** [comment]
@bhushankhope thank you for getting this started! The text seems thinner and spaced out in the preview vs. [the spec](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Design-System-Components?node-id=190-17&t=4nefbd155tr054Fl-4). Mentioning @axdanbol for visibility, too.

Right now, we use two different logos in two specific instances. The white logo is used in the footer and the black logo is used until the 1013px breakpoint.

There are no plans to use other variants elsewhere in our UIs in Y3. The HRA logo component has to match the specifications exactly. It would be amazing to use the approved image for 100% accuracy.

![image](https://github.com/user-attachments/assets/3a5269af-401e-4cc1-85e2-e4b8535afad6)

**Comment by bhushankhope** [comment]
@LibbyUX now we are using the svg itself. Please review [here](https://github.com/hubmapconsortium/hra-ui/pull/590#issuecomment-2256603449)
