### ISSUE TITLE
Button: Card - HuBMAP Apps

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#586]
# Button: Card - HuBMAP Apps
- Design System Components: [Button: Card - HuBMAP Apps](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Design-System-Components?node-id=78-355)
- Google Spreadsheet: [HuBMAP Tools for Shared Navigation Component](https://docs.google.com/spreadsheets/d/12obX2cWD6Sw3L0IWXMs47LT4YyBJEKbxNUCcNLqM98w/edit?pli=1&gid=0#gid=0)

<img width="1821" alt="Screenshot 2024-07-25 at 3 59 26 PM" src="https://github.com/user-attachments/assets/61421d27-780f-480c-88d5-185b24579a97">

## Building Blocks
- App icons
- Font styles
  - Product Titles
    - Color: HRA Blue
    - Font style/size: Label Large
  - Product descriptions
    - Color: HRA Blue 2
    - Font style/size: Label Medium
- Responsive: These buttons are responsive and shrink and grow as needed

## Usage
- HuBMAP's HIVE UX/UI Cross Collaboration team has created a menu to connect HuBMAP applications cohesively. This menu is accessed by clicking the apps icon button in our new navigation headers.
  - These buttons are used HuBMAP App Side Nav Overlay Menu. See #557 for the full component.
  - Eventually, these buttons will be used in longer mobile side nav menus, for breakpoints 1012px and below.

### Variants
- Products
  - HuBMAP Consortium
  - HuBMAP Data Portal
  - Data Portal Workspaces
  - Human Reference Atlas
  - Exploration User Interface
  - ASCT+B Reporter
  - Azimuth
  - FUSION
  - Antibody Validation Reports
- States
  - Ready/default
  - Hover
  - Active/pressed
  - Focus
  - Focus visible

## Behavior
- Clicking on any of these products always opens a new tab, unless they are currently on the HRA, EUI, or ASCT+B Reporter.
  - Note that this menu has only been specified for certain products so far, like the FTU Explorer and the CDE. This functionality will be added to all UIs eventually.
- We chose to add periods at the end of all of the product descriptions. Note that this varies from and overrides how people filled out the [HuBMAP Tools spreadsheet](https://docs.google.com/spreadsheets/d/12obX2cWD6Sw3L0IWXMs47LT4YyBJEKbxNUCcNLqM98w/edit?pli=1&gid=0#gid=0).

**Comment by LibbyUX** [comment]
Update: [HuBMAP-styled variant](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Design-System-Components?node-id=114-1244&t=0HHzWqjF6QlbPMGp-4) added to the Design System Repo & Component file.

**Comment by LibbyUX** [comment]
Update: Still tinkering with HuBMAP-styled variants - I will have this finalized soon.

**Comment by LibbyUX** [comment]
Update: HuBMAP Style variants will not be in the design system. Stay tuned for a separate issue for these. These components are ready for dev. Thanks!

**Comment by bhushankhope** [comment]
@LibbyUX Here is the preview for this component
[link](https://github.com/hubmapconsortium/hra-ui/pull/637#issuecomment-2284553142)
