### ISSUE TITLE
Implement HuBMAP navigation component on current humanatlas.io

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#591]
# HuBMAP navigation component on current humanatlas.io
This is a high-priority request: Please implement new HuBMAP apps navigation on humanatlas.io

## Mobile and Desktop
![image](https://github.com/user-attachments/assets/c982a69e-3808-4a67-bfa3-98dd8763e65d)

## Behavior
- The menu will need a scrolling area if the page height is smaller than the menu options.
- Button cards have two states: Ready and hover.
- All button cards open in a new tab.

## Figma
- [HuBMAP Apps Components](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/HRA-2022-2024-(HuBMAP-Styles)?node-id=6188-5575&t=2dkHJg8GaiWH4UwB-4)

**Comment by LibbyUX** [comment]
Mobile behavior request: Is it possible to only have one category open at a time with the mobile menu? This is a behavior I've been observing in websites like Figma. No worries if this can't happen, but just wanted to ask. I will for sure specify this on our HRA design system mobile overlay menus. Thanks for getting this started, @bhushankhope!

**Comment by bhushankhope** [comment]
Added the menu for both web and mobile view
preview [here](https://github.com/hubmapconsortium/hra-ui/pull/613#issuecomment-2271956664)

**Comment by LibbyUX** [comment]
@bhushankhope Thank you! I reviewed the PR linked above that is merged into develop. Feel free to assign me as a reviewer relevant PRs now that I'm back in the office!

This looks great! Is it possible to do one category open functionality?

I'll close this issue when it's merged into main. Thanks so much!

**Comment by bhushankhope** [comment]
@LibbyUX Implemented the above functionality for mobile menu. Preview [here](https://github.com/hubmapconsortium/hra-ui/pull/623#issuecomment-2278424790)

**Comment by LibbyUX** [comment]
It's looking good, @bhushankhope! We are super close! One small request: Is it possible to remove the horizontal scroll bar. It shows for the first 4 categories, but I don't see it on About or HuBMAP Tools and Applications. 

![image](https://github.com/user-attachments/assets/1727ca1f-2939-4b16-82f6-65095c9c6668)

**Comment by bhushankhope** [comment]
@LibbyUX fixed it
[link](https://github.com/hubmapconsortium/hra-ui/pull/623#issuecomment-2278424790)

**Comment by LibbyUX** [comment]
@bhushankhope - Perfect. Approved from the design end! Thank you!

**Comment by LibbyUX** [comment]
@bhushankhope thanks so much!
