### ISSUE TITLE
Header: Nav Header

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#592]
# Header: Nav Header
Implement [Nav Header in the Design System Storybook](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Design-System-Components?node-id=0-1).
- Functional Tissue Unit Explorer
- Cell Distance Explorer

## Behavior
- Scrolls with page
- Apps icon opens #557 
- No max width
- Two width based variants:
  - +1920px to 1013px: Uses larger logo buttons, generally
  - 1012px to 320px: Uses smaller logo buttons
    - If other navigation categories are present, the HuBMAP apps button switches to a menu button, which opens a sidenav for all navigation categories. The HuBMAP apps menu items are contained at the bottom of the sidenav.

![image](https://github.com/user-attachments/assets/7289134e-e781-4771-b114-cd98c4596beb)

**Comment by bhushankhope** [comment]
@LibbyUX 
Please review this [here](https://github.com/hubmapconsortium/hra-ui/pull/621#issuecomment-2276385123)
The apps button wont work now, Edward is currently working on the menu
