### ISSUE TITLE
Bug Report: Organ Carousel Fails to Expand When Pressing Down Arrow

### ISSUE THREAD

**Issue by danqaurooni** [hubmapconsortium/hra-ui#596]
The organ carousel (the top pane) in the EUI fails to expand after clicking the down arrow. What you get is a blank space (See screenshot.) You would have to first click the right arrow to get the carousel to populate the space with organs.

<img width="751" alt="Screenshot 2024-07-30 at 13 04 38" src="https://github.com/user-attachments/assets/85ea0bdb-340b-4edd-9824-52d172deaac6">

<img width="741" alt="Screenshot 2024-07-30 at 13 09 56" src="https://github.com/user-attachments/assets/07b84aed-44da-4647-8c87-aa42cd09746e">

OS: MacOS
Browser: Chrome

**Comment by bherr2** [comment]
Yes, I've seen the same behavior and needs corrected.

**Comment by axdanbol** [comment]
@bherr2 Fix has been merged to develop
