### ISSUE TITLE
Hepatocyte showing in FTU Explorer for kidney FTU

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/hra-ui#615]
@katyb @bherr2 @supriyabidanta 

I saw hepatocyte, liver CT, in the data for a kidney FTU, for some reason: https://github.com/hubmapconsortium/hra-ui/blob/main/apps/ftu-ui/src/assets/TEMP/ftu-cell-summaries.jsonld

In FTU Explorer, see on right:
<img width="1427" alt="image" src="https://github.com/user-attachments/assets/9e5fc1d8-173e-4cfc-b620-2c27c10907b0">

**Comment by andreasbueckle** [comment]
PS: There are also lung secretory cells and airway cells in the table for the kidney FTU:
![Uploading image.png…]()

**Comment by LibbyUX** [comment]
@andreasbueckle, @bherr2 - Has this been completed? This is what I see today:

![image](https://github.com/user-attachments/assets/0b73e690-2d56-4d07-90c3-e609432e4541)

**Comment by andreasbueckle** [comment]
Yes, it appears that this is completed. We are still fixing the issue of why the hepatocyte (liver cell) appears in other organs (due to popV): https://github.com/hubmapconsortium/hra-workflows-runner/issues/37

**Comment by LibbyUX** [comment]
Thank you @andreasbueckle !
