### ISSUE TITLE
Add violin plot module to visualization application

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#627]
![image](https://github.com/user-attachments/assets/a0cca731-0983-48c0-b93c-818555b2a97c)

@bherr2 are we using Vega-lite for the Violin plot? What technical details should I keep in mind while designing?

**Comment by bherr2** [comment]
We don't have a slam dunk violin plot from vega-lite, but I think we'll be able to make it work. So, I'd suggest not trying to add too many bells and whistles for the first version so we can just focus on getting something functional. After that we can see how we can go beyond.

Examples:
* https://observablehq.com/@vega/vega-lite-distribution-plots
* https://vega.github.io/vega-lite/docs/density.html (what will likely be the driver with some tweaking)
* https://vega.github.io/vega/examples/violin-plot/ (vega (not -lite) version)

**Comment by LibbyUX** [comment]
### Status Update
- 8.12.2024: Yash shares [VCCF Visualization presentation slides](https://docs.google.com/presentation/d/197_1T85MoGNAxHdztliZoC62zoQvenP6wV9hW0j66fU/edit#slide=id.g2dc9753afd7_0_390) containing statistics/visualizations per organ.
- 8.14.2024: This was identified as priority 2 for the November paper, see #489 
- We are getting closer to a finalized MVP2 violin plot module design:

![image](https://github.com/user-attachments/assets/0636e8e8-b3fc-4070-84c2-6dcc1ff89ae0)

### To Do
- Design full screen modal
- Design consolidate cells/button interaction
- Design guide modal for this module

**Comment by LibbyUX** [comment]
![image](https://github.com/user-attachments/assets/55584a58-7bc1-44d9-a406-b874cb930efb)

# Violin Graph Module
- [Component](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=3145-18986&t=TNPV3og4jZMA4eMq-4)
- [More Menu Options](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2864-6376&t=TNPV3og4jZMA4eMq-4)

## Behavior
- When users show/hide cells or alter colors of cells in the Cell Types module, updates occur in the violin plot.
- When users delete cells/links spatially in the visualization module, they are removed from the violin plot as well.

![image](https://github.com/user-attachments/assets/9a8f44a3-24e3-487b-9ccd-fbbec99eae85)

![image](https://github.com/user-attachments/assets/00572146-c725-4dc7-a32c-780332ae6b7c)

Adding a mention for @edlu77 regarding this component. Happy Friday!

**Comment by LibbyUX** [comment]
Thanks so much, @edlu77 & @axdanbol!
