### ISSUE TITLE
Add full screen mode to vis app

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#640]
# Add full screen mode to vis app
- All vis/plot modules: Full screen modal overlay for visualization & plots
  - Users can tab between two views in this modal: visualization or plots
  - Users can close out of full screen with an "X" close icon button in the top left to return to the regular vis app

### Current iteration
Note: Things will change in this initial screenshot of the UI in canvas with mat-menu entry points
![image](https://github.com/user-attachments/assets/095ce8fe-e5ab-4e10-bdc2-12dc16575530)

**Comment by LibbyUX** [comment]
# Ready for dev
Add full screen mode to vis app modules: visualization, histogram, and violin graph
- [Figma: Full screens](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=3026-13977&t=TNPV3og4jZMA4eMq-4)

![image](https://github.com/user-attachments/assets/7b50c442-cbe3-41b4-a593-b79ba910f0ad)

**Comment by bhushankhope** [comment]
Currently in cde-mvp2 branch, fullscreen working well for histogram, but needs work on violin plot and vsualization
