### ISSUE TITLE
Add new functionality to vis app's visualization module

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#643]
# Add new functionality to visualization module
The visualization module needs states so that users can interact with the visualization:
- Explore: Move around the cell distance visualization to a desired location. Currently implemented functionality.
- Inspect: Users receive informational cards on hover or click of nodes/edges. Cells/nodes to receive cell ID, all available coordinates, distance to closest anchor cell. Anchor cells could show the different cell type connections + distances.
- Select: Lasso freeform drawing selection tool state with the functionality to draw in the visualization, select, deselect, show, and hide certain areas to improve analysis.

@bherr2 + @J-Yash - Please let me know if you have any questions or feedback on the direction of this design:
![image](https://github.com/user-attachments/assets/7015d866-7239-44fa-8d1e-4af7926bb199)

**Comment by LibbyUX** [comment]
### Selection tool minimum needs for users/paper:
@bherr2, after speaking with @J-Yash today, it's clear that the selection tool is needed to clean up segmentation artifacts spatially in people's data. Users need to select areas within the visualization to delete them. By deleting, they remove those nodes from the current visualization module, both plots, cell types list, and subsequent downloads.

### Nice to have's
- Ideally, we have an undo button/keyboard shortcut for deletion actions. UX best practices provide ways to remedy errors.

**Comment by LibbyUX** [comment]
![image](https://github.com/user-attachments/assets/7c8c7c5b-e712-4198-9ae6-063a68aead88)

# Visualization module MVP2:
- Explore mode: Current implementation and functionality. No changes.
- Inspect mode:
  - Nodes expand visually so they are easier to see/click
  - Clicking a node opens a modal/overlay with all available information about the specific cell type
- Select mode:
  - Users can no longer rotate the view in selection mode
  - Lasso selection tool for selecting and deleting segmentation artifacts
  - Deleting a selection removes it from the visualization module, cell types module, and histogram module, and the data downloads from those modules
  - Users may reset deleted cells with the reset button in the menu
    - I want to expand upon this functionality eventually with undo and redo + keyboard shortcuts
  - Users may one work with one lasso selection at a time in this version
- Like other visualization modules, full screen mode is also an option

### Figma
- [Visualization module component](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2897-44015&t=4MNOGlwgjiv4rtZa-4)
- [Vis module menus and tooltips](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2864-6374&t=4MNOGlwgjiv4rtZa-4)
- [Vis App](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2704-25852&t=4MNOGlwgjiv4rtZa-4)

<img width="1215" alt="Screenshot 2024-09-06 at 7 57 02 PM" src="https://github.com/user-attachments/assets/d6e1a700-5dff-4562-b170-e46541f9f9b4">

<img width="1319" alt="Screenshot 2024-09-06 at 7 59 12 PM" src="https://github.com/user-attachments/assets/b5fb742f-98b0-46e0-9a3d-e9eb67e4d1be">

**Comment by bhushankhope** [comment]
Design is ready, but all actions are not ready. Currently in cde-mvp2 branch.
