### ISSUE TITLE
Update: 7th release ASCT+B table on humanatlas.io has 2 instances of bone marrow

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/hra-ui#656]
@bherr2 
Given automatic processing for 7th release where some file naming schema changed, it appears that we have 2 different versions of ASCT+B table present in "7th release" when there should only be 1.   

Bone marrow v1.5 is correct, but bonemarrow pelvis is OLD release and should not be part of 7th release "new" version files.

This will most likely mess up the ASCT+B reporter too?

Regarding "latest" versioning?

<img width="384" alt="bonemarrowASCT+BScreenshot 2024-08-19 at 1 59 08 PM" src="https://github.com/user-attachments/assets/3af2422c-640b-4b65-98a4-0ce88bb2e0c4">

**Comment by emquardokus** [comment]
@bhushankhope please update the [humanatlas.io](http://humanatlas.io/) site by manually removing the row corresponding to "bonemarrow pelvis v1.3"
Bruce removed from here https://lod.humanatlas.io/collection/hra/v2.1/ does not have 'bonemarrow-pelvis' anymore, but did not make the corresponding update to the humanatlas.io https://humanatlas.io/asctb-tables

Remove this row in photo: 
<img width="460" alt="Screenshot 2024-08-30 at 12 10 45 PM" src="https://github.com/user-attachments/assets/07f3ca52-260c-40be-aea4-275a09abeaa8">

**Comment by LibbyUX** [comment]
@emquardokus - Just want to check in: Has this been completed?

**Comment by emquardokus** [comment]
> @emquardokus - Just want to check in: Has this been completed?

It has **not** been fixed; or if fixed, not merged to main so it’s correct on website.

**Comment by LibbyUX** [comment]
> > @emquardokus - Just want to check in: Has this been completed?
> 
> It has **not** been fixed; or if fixed, not merged to main so it’s correct on website.

Thank you for the update, @emquardokus. I went through our issues with the high priority label yesterday. Looping @bherr2 in: I updated the status of this to ready for dev. Please let me know if I can do anything more to assist on this, I appreciate y'all!

**Comment by axdanbol** [comment]
Fix merged to develop. Will merge to main by EOD (12/18)
