### ISSUE TITLE
Button Toggle

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#665]
# Button Toggle
[Angular Material Button Toggle](https://material.angular.io/components/button-toggle/overview#button-toggle-mode) in HRA styles:
- We will need exclusive select and multi-select functionality for this button
  - Single-select needed for future versions of CDE and Atlas Apps
  - Multi-select needed for future versions of EUI
  - More UIs will use a segmented button eventually

### Resources
- [Design System Components](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Design-System-Components?node-id=853-284)
- [Design System Repo](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=5272-20704&t=Oeqj9GgvHkceIYsw-4)
- [Design System Repo: Button Toggle Building Blocks](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=4937-19480&t=Oeqj9GgvHkceIYsw-4)
- #562 

![image](https://github.com/user-attachments/assets/a2b046ab-0e25-45ae-9354-a883e43a9649)

![image](https://github.com/user-attachments/assets/78d78972-45ba-4477-b94f-a6c186061a4d)

**Comment by LibbyUX** [comment]
@bhushankhope & I caught up just now about the need for this to occasionally have a fill behavior within certain containers. I also noticed I needed a medium sizes component. This component will always be designed in a container with a minimum width, so it responds correctly for users.

Please see updated:
- [Design System Repo](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=5272-20704&t=XPC6OgGjqCjcTJ2t-4)
- [Design System Components](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Design-System-Components?node-id=853-284)

![image](https://github.com/user-attachments/assets/1d51b505-351b-4c5f-8d47-ed669731bf55)


## Examples
### FTU
- [Fill single select](https://www.figma.com/design/VlNjSrctLEc0Wyu32FmnZq/Functional-Tissue-Unit-(FTU)-Explorer?node-id=6284-17583&t=koznq4eNTuTI9VLg-4)

![image](https://github.com/user-attachments/assets/6ec5a471-4320-43d7-b7fc-99cd78592689)

### CDE
- [Condensed/hugged single select](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2704-27313&t=01L09AVNnpy2rB0a-4)

![image](https://github.com/user-attachments/assets/d7e16cdb-618d-442a-97ca-fdc25abbc72a)

**Comment by bhushankhope** [comment]
@LibbyUX updated the styles. Please review [here](https://github.com/hubmapconsortium/hra-ui/pull/671#issuecomment-2307333300)

**Comment by bhushankhope** [comment]
@LibbyUX Working on it. Thanks

**Comment by bhushankhope** [comment]
@LibbyUX please review. Thanks
[Link](https://github.com/hubmapconsortium/hra-ui/pull/695#issuecomment-2332335422)

**Comment by LibbyUX** [comment]
Superseded by #775
