### ISSUE TITLE
Form Field: Mat-Input

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#666]
# Form Field: Mat-Input
[Angular Material's Form Field Mat-Input](https://material.angular.io/components/form-field/overview#form-field-overview) in HRA styles:
- Two appearance variations: Fill + outline
  - Currently we are using the fill for new iterations of the CDE.
  - I haven't specified anything with the outline variation yet but it would be a nice option to have ready to go, if it's needed.
- Small + hidden title variant usage: Color value inputs only. Currently only used in the new iteration of the color picker component for the CDE.

### Resources
- [Design System Components](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Design-System-Components?node-id=856-366)
- [Design System Repository](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=5216-21586&t=Oeqj9GgvHkceIYsw-4)

![image](https://github.com/user-attachments/assets/5e51e2ae-c344-47a3-93d4-a3a7924b44eb)

![image](https://github.com/user-attachments/assets/adee1a06-997a-4d5c-a55f-70ebbebcb92e)

![image](https://github.com/user-attachments/assets/f6623dd4-4d18-47fb-9871-aa7810feac9e)

**Comment by bhushankhope** [comment]
@LibbyUX I have created the inputs. Please review once. Preview [here](https://github.com/hubmapconsortium/hra-ui/pull/674#issuecomment-2310858694). Let me know if anything needs to be changed. Thanks

**Comment by LibbyUX** [comment]
This is completed up to as specified on Aug 26th. Closing. Will add a new issue when Design System iteration update is needed. Thanks!
