### ISSUE TITLE
Update organ name from purl to label on Cell Type Annotation page

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/hra-ui#683]
In the table, one of the organs shows up as a purl instead of a organ name: 
<img width="1132" alt="Screenshot 2024-08-30 at 8 57 00 AM" src="https://github.com/user-attachments/assets/1179c38d-a3ce-40e4-9a01-3a433b08ad32">

http://purl.obolibrary.org/obo/UBERON_0001347 should show up as white adipose tissue

**Comment by bhushankhope** [comment]
@emquardokus Fixed it. Please review [here](https://github.com/hubmapconsortium/hra-ui/pull/685#issuecomment-2321455090). Visit this link and click on humanatlas.io under Apps.
