### ISSUE TITLE
ADD Peripheral Nervous System to Organ crosswalk to VCCF page

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/hra-ui#684]
To this webpage https://humanatlas.io/vccf on humanatlas.io, please add the [peripheral-nervous-system-organ-crosswalk](https://lod.humanatlas.io/asct-b/peripheral-nervous-system-organ-crosswalk/) to the table. 

**Organ:** peripheral nervous system to organ crosswalk
**Download HRA-VCCF File :**    csv  linked to  https://lod.humanatlas.io/asct-b/peripheral-nervous-system-organ-crosswalk/v1.0/
**Release Version:** v1.0
**Digital Object Type:** crosswalk

**Comment by bhushankhope** [comment]
@emquardokus Fixed it. Please review [here](https://github.com/hubmapconsortium/hra-ui/pull/685#issuecomment-2321455090). Visit this link and click on humanatlas.io under Apps.

**Comment by LibbyUX** [comment]
@emquardokus - Status check on this one! Are we completed or does this still need work?

**Comment by emquardokus** [comment]
> @emquardokus - Status check on this one! Are we completed or does this still need work?

this was completed, see https://humanatlas.io/vccf

**Comment by LibbyUX** [comment]
Thank you @emquardokus - I am closing as completed!
