### ISSUE TITLE
Dialog: Notice

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#688]
# Dialog: Notice
All websites need a screen resolution modal variant. Thank you!
- [Design System Repo](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Explorer-Design-System-Repository?node-id=4941-18730&t=02sx3cSIpiSo7tOm-4)
- [Explorer Components](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Explorer-Components?node-id=1115-364)

<img width="876" alt="Screenshot 2024-08-31 at 12 49 04 PM" src="https://github.com/user-attachments/assets/b7a3dcac-5a58-4b13-bcf6-41a0c88d2d29">

**Comment by LibbyUX** [comment]
Note: Users may click outside the dialog to close it.

**Comment by bhushankhope** [comment]
@LibbyUX I have created the dialog. Please review [here](https://github.com/hubmapconsortium/hra-ui/pull/707#issuecomment-2343854302). Thank you!
