### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#690]
# Color Picker
Please add the new color picker and related molecules to Storybook.
- [Design System Repo](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Explorer-Design-System-Repository?node-id=5782-24855&t=A6X26dDTAmrSZ49F-4)
- [Explorer Components](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Explorer-Components?node-id=1117-10518)

<img width="1584" alt="Screenshot 2024-08-31 at 2 33 34 PM" src="https://github.com/user-attachments/assets/343dcb4c-b025-4883-b2c2-86d73b069db5">

**Comment by LibbyUX** [comment]
Thanks for meeting with me just now @bhushankhope! I will iterate on our current color picker component to better fit within the technical structure of the [ngx color picker](https://zefoy.github.io/ngx-color-picker/). I will ping you here when this design is ready!
- Design to do:
  - Create a way to navigate color format types with buttons instead of Select/dropdown UI
  - Remove number input for HEX opacity
<img width="516" alt="Screenshot 2024-09-05 at 11 12 04 AM" src="https://github.com/user-attachments/assets/33c9efa3-975e-463e-a50e-e6bcf5018a27">

### Later versions side note for @bherr2 + @axdanbol:
- Is it possible to eventually work towards the color picker I initially specified with a dropdown to select the color format type and an opacity percentage input for HEX codes? I drew my UI inspiration from Figma's color picker. Maybe we can work towards this initial design during design system expansion? Just let me know! Thanks for everything!

<img width="1460" alt="Screenshot 2024-09-05 at 11 19 28 AM" src="https://github.com/user-attachments/assets/58d93e1e-80fe-4c7e-8335-a3fe09c5699d">

**Comment by bherr2** [comment]
To get to where you want will likely mean us implementing our own color picker component rather than customizing an existing one. This will introduce a fairly significant engineering hit that we'd rather reserve for other higher priority items. 

As for if it can be done in the future, absolutely, but needs to be taken into consideration with other priorities. Perhaps next cycle.

**Comment by LibbyUX** [comment]
@bhushankhope - How does something like this look for the updated color picker? This is an button with an icon, not a dropdown. Let me know if this is doable.

![image](https://github.com/user-attachments/assets/3ba65de4-9b8b-4216-a45a-7902ab086273)

**Comment by LibbyUX** [comment]
@bhushankhope, please see [Color Picker](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Explorer-Design-System-Repository?node-id=5834-21780&t=PGgdVBJSN0RcHOcM-4) and let me know when it's ready for review. Thanks so much!

![image](https://github.com/user-attachments/assets/d7384d40-49c1-4fed-9229-93c10f25186f)

**Comment by bhushankhope** [comment]
@LibbyUX I have made the changes, please review from [here](https://github.com/hubmapconsortium/hra-ui/pull/692#issuecomment-2329784016). Thanks
