### ISSUE TITLE
HRA Organ information is not generated when a user is not logged in (SenNet)

### ISSUE THREAD

**Issue by maxsibilla** [hubmapconsortium/hra-ui#702]
This can be reproduced by visiting any organ page on the SenNet Data Sharing Portal (e.g. https://data.sennetconsortium.org/organs/heart) while not logged in or in incognito mode. The default token that gets set is `55488bfad6fa6946e15209040938668e` which is not valid for SenNet and prevents any public block information from being gathered. The default behavior when no token is passed should be to not set it at all.

<img width="1495" alt="image" src="https://github.com/user-attachments/assets/b77c8c47-7fd6-4554-b649-39da4948be5e">

**Comment by bherr2** [comment]
The other token is an HRA-API session token, so ignore that. But I do see you are passing 'undefined' to the sennet ds-graph endpoint: 
![image](https://github.com/user-attachments/assets/6d763ca3-2b39-4887-a90c-93a280e8225f)

Which causes an error. I believe that is the root of the issue. if you just replace undefined with the empty string and produce this url `https://apps.humanatlas.io/api/ds-graph/sennet?token=` it should work again.
