### ISSUE TITLE
Error Indicator

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#716]
# Error Indicator
### Figma
- [Design System Repo](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Explorer-Design-System-Repository?node-id=5864-21928&t=PGgdVBJSN0RcHOcM-4)
- [Explorer Components](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Explorer-Components?node-id=1294-4977)

Please add our new Error Indicator component to the design system:
- Error indicators appear on Workflow Cards, see #712. Workflow cards are currently found in the CDE and the App Library.
- Errors need to kindly guide users to success.
- I am using Figma text string variables to keep our error text consistent. Below are the error message text variations from the CDE & App Library approved specifications:

![image](https://github.com/user-attachments/assets/4910b4d2-ef75-463a-9bcd-63a412432527)

# Examples
### CDE
![image](https://github.com/user-attachments/assets/a0c8c861-49f7-463a-a447-6f63a3fd7363)

### App Library/Tissue Origin Predictor
![image](https://github.com/user-attachments/assets/a7b81d3b-2abc-4642-a53c-7c6cc62e5ac8)

**Comment by LibbyUX** [comment]
@edlu77 - Thanks for the productive conversations today on error indicators!

I updated:
- [Design System Repo](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Explorer-Design-System-Repository?node-id=5864-21928&t=pFkF1PQUuNDPlHtf-4)
- [HRA Components](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/Explorer-Components?node-id=1294-4977)

![image](https://github.com/user-attachments/assets/99a1167e-326c-4e27-9091-04074b8420b2)

**Comment by bhushankhope** [comment]
@LibbyUX Please review [here](https://github.com/hubmapconsortium/hra-ui/pull/741#issuecomment-2377882982). Thanks
