### ISSUE TITLE
Bug Report: SenNet Embedded RUI Misrepresents Tissue Block

### ISSUE THREAD

**Issue by danqaurooni** [hubmapconsortium/hra-ui#761]
A user reported the bug below and I have been able to verify it on my end:

I've found an odd bug when using some registration JSON files (I have 4 such cases, attached). The two pancreases have different orientation and shape. In the SenNet portal the block 018c is clearly off.
![image](https://github.com/user-attachments/assets/f54ba40d-d0f9-46db-8e81-16aa43c02299)

However when I load same JSON in the HuBMAP RUI, I see proper block position:
![image](https://github.com/user-attachments/assets/7ab82753-7121-48e4-a969-f3d154d99bbb)

[JDC_WP_017_b_registration-data - 2024-08-07T120220.440.json](https://github.com/user-attachments/files/17247892/JDC_WP_017_b_registration-data.-.2024-08-07T120220.440.json)
[JDC_WP_017_h_registration-data - 2024-08-07T120418.066.json](https://github.com/user-attachments/files/17247893/JDC_WP_017_h_registration-data.-.2024-08-07T120418.066.json)
[JDC_WP_018_c_.json](https://github.com/user-attachments/files/17247894/JDC_WP_018_c_.json)
[JDC_WP_018_j_.json](https://github.com/user-attachments/files/17247895/JDC_WP_018_j_.json)

**Comment by bherr2** [comment]
Oh, I see one issue is that one is using the *Male* pancreas and the other is using the *Female* pancreas. Look at the screenshots again.
