### ISSUE TITLE
Design tweaks to modules: Metadata & Histogram

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#770]
# Design tweaks to modules: Metadata & Histogram
Small design tweaks have been added to the Metadata/Sample Metadata module and the Histogram module:
- Add "More" icon button with micro tooltip `More` on hover
- Add micro tooltips for `Expand` and `Collapse` on hover of Minus and Plus icon buttons
- Add menus for both modules:
  - [Metadata/Sample Metadata](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2864-6298&t=ALRbKMRiO7vJ36yk-4)
  - [Histogram](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2864-6380&t=ALRbKMRiO7vJ36yk-4)
    - Users will receive a snackbar when downloading files from our menus.

### Histogram module tweaks
- Add full screen mode: #640 
- Legend: Remove scrolling listing for the current legend. This was redundant so we removed it.
  - Add "All Cells" area in the Histogram. On click of the color swatch button, users receive the color picker flyout for all cells in the histogram.
### Metadata/Sample Metadata module tweak
- Update the styles of the metadata listing

### Design system open issues
- #755 

## Figma
- [Histogram](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2704-27358&t=ALRbKMRiO7vJ36yk-4)
  - [Menus & tooltips ](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2864-6380&t=ALRbKMRiO7vJ36yk-4)
  - [Full screen mode](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2919-7466&t=ALRbKMRiO7vJ36yk-4)
- [Metadata/Sample Metadata](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2929-7816&t=ALRbKMRiO7vJ36yk-4)
  - [Menus & tooltips](https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2864-6298&t=ALRbKMRiO7vJ36yk-4)

### Current implementation
![image](https://github.com/user-attachments/assets/0956826b-07c9-446a-b5f9-a1cd3f9517b0)

### Approved specification
![image](https://github.com/user-attachments/assets/6420e2fc-38b8-4034-afa8-f1c6b0888d15)

**Comment by bhushankhope** [comment]
@LibbyUX please review the metadata module (here)[https://github.com/hubmapconsortium/hra-ui/pull/772#issuecomment-2397690645]
