### ISSUE TITLE
HRA Portal version preservation

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#771]
@bherr2, is it possible to preserve the current version of the HRA portal at `humanatlas.io` temporarily? I'm not sure of the exact timeframe needs, however, an initial guess would be until July 2025, or maybe always, like we did with the CCF Portal.

I have started working on newer iterations of our redesigned HRA portal. I want to give Katy the option to go back to the current implementation, after we implement the design system alignment version by Dec 13th.

## Current implementation: Home
- https://humanatlas.io/

![image](https://github.com/user-attachments/assets/f9184dd5-6988-4e61-817b-777b23e514a1)

## Mid-iteration: Redesigned landing page
- [Figma](https://www.figma.com/design/AwS7caXwnBn1AqgiG93Zxn/HRA-Redesign-2024-(Human-Reference-Atlas)?node-id=3438-11749&t=xyGI3avQ0VKs0NTw-4)

![image](https://github.com/user-attachments/assets/f0467833-07e3-41f2-9820-e64adbafe9e2)

## Proposed navigation structure
- [Figma](https://www.figma.com/board/H3CK8StFdAphCFtFAHAwhM/Information-Architecture?node-id=791-2406&t=Cy61zeZV9XDgWKuu-4)

![image](https://github.com/user-attachments/assets/ce7bf56c-34c7-495d-b596-1a35988175d5)

**Comment by bherr2** [comment]
There are some options. Let's discuss after I'm back on Thursday.

**Comment by LibbyUX** [comment]
Thanks for catching up on this today with me, @bherr2! We will discuss our options and the desired vision for this feature with @katyb during UX Specs on October 23rd.

**Comment by LibbyUX** [comment]
I'm closing as not planned, @bherr2. I will submit something new in a different direction, if needed. Thanks for the collaboration on this!
