### ISSUE TITLE
Button toggle updates

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#775]
Please update our Storybook to match Figma:
- Cosmetics for our current [button toggle atom (states)](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/HRA-Design-System-Repository?node-id=6139-41123&t=D81QR6nmRJB6HR8r-4) & [button toggle component](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/HRA-Design-System-Repository?node-id=5272-20704&t=D81QR6nmRJB6HR8r-4)
- Add a small variation
  - [Atoms](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/HRA-Design-System-Repository?node-id=6170-22863&t=D81QR6nmRJB6HR8r-4)
  - [Component](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/HRA-Design-System-Repository?node-id=6139-41152&t=D81QR6nmRJB6HR8r-4)

## Resources
- [HRA Components](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/HRA-Components?node-id=853-284)
- [Design System Repo](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/HRA-Design-System-Repository?node-id=6139-36975&t=D81QR6nmRJB6HR8r-4)
- Relevant for several ready for dev issues:
  - #643 
  - #323 
  - #729 
  - #733 
  - #652 
  - #570 

![image](https://github.com/user-attachments/assets/40636a71-c4c6-4563-a669-c9bc8cf7c22c)

**Comment by bhushankhope** [comment]
fixed in #776
