### ISSUE TITLE
Icon button cosmetic & organization updates

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#782]
Please:
- Remove all sizes besides
  - 40x40 target size/24x24 Material Icon
  - 24x24 target size/20x20 Material Icon
- Rename them to 40x40 and 24x24
- Use new specified state colors
  - See: #751 

### Resources
- [Design System Repository](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/HRA-Design-System-Repository?node-id=1975-1693&t=9r8hL3TwsxUvttGx-4)
- [HRA Components](https://www.figma.com/design/BCEJn9KCIbBJ5MzqnojKQp/HRA-Components?node-id=24-876)
- #751

**Comment by bhushankhope** [comment]
fixed in #785
