### ISSUE TITLE
8th Release SOP page updates

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#852]
# Ready for dev

Please update the SOPs page (https://humanatlas.io/standard-operating-procedures) with Lisel's Google Doc: [HRA-Table of Contents](https://docs.google.com/document/d/1Q-Fyi1N1uSwFvE4FBpFL9kvylLSbpElxHaYEVvgucNs/edit?tab=t.swu4dsjwab1h).

She has highlighted all new updates within the comments and provided links to use.

She is also requesting we delete two SOP titles/routes in the current content:
- [Using the CCF Registration User Interface (RUI)](https://doi.org/10.5281/zenodo.5575776)
- [Assigning RUI Data to Multiple Tissue Blocks](https://doi.org/10.5281/zenodo.5746143)

Please let us know if you have any questions! Thank so much!

![image](https://github.com/user-attachments/assets/579362d3-ee3b-48b1-91a2-c5e1f7fb301a)

**Comment by LibbyUX** [comment]
@bherr2 & @axdanbol - Please see this issue and let me know if there is anything I can do to support. Lisel and @emquardokus pinged me looking for this page update just now!

**Comment by emquardokus** [comment]
@bherr2 @axdanbol @LibbyUX 
This pull request fulfills this request https://github.com/hubmapconsortium/hra-ui/pull/872 plus fixes an issue on vccf.yaml page.
