### ISSUE TITLE
Update release announcement card with 8th release info

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#859]
# Ready for dev
Please update this text to read:
`The 8th Release of the Human Reference Atlas (v2.2) is now available! See what's new in HRA v2.2 in 8th Release Notes.`

We will need to route to the new release notes page. More info on that content coming this afternoon!

![image](https://github.com/user-attachments/assets/e3221b0a-90e9-481e-8b66-fdb6f7d40cbb)

**Comment by LibbyUX** [comment]
@bherr2 @axdanbol - I am checking out the new HRA Portal now: It's looking great! I still see this card needs to be updated, please see this issue and reach out if you need anything!

**Comment by bherr2** [comment]
Fixed on production https://humanatlas.io/
