### ISSUE TITLE
8th release: omaps_release7.csv and omaps_release8.csv

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/hra-ui#865]
[omaps_release8.csv](https://github.com/user-attachments/files/18128921/omaps_release8.csv)
updated omap-2, omap-9 and omap-21 for versions across all columns, add omap-22 and omap-23 for all information.

[omaps_release7.csv](https://github.com/user-attachments/files/18129070/omaps_release7.csv)
Updated omap-20 to have imagingMethod to IMS-CyCIF from CyCIF, also added rep dataset for omap17 and omap-18

**Comment by bherr2** [comment]
Updated in https://github.com/hubmapconsortium/hra-ui/pull/867
