### ISSUE TITLE
Uploading a RUI JSON adds previously removed AS tags back in

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/hra-ui#866]
Let's say I make a registration and before I download, I have 2 AS tags. Then I remove AS1 and download the JSON. When I upload the JSON file, AS1 shows back up.

Tested on Chrome.

**Comment by bherr2** [comment]
Let's talk about this one at standup

**Comment by andreasbueckle** [comment]
From 12/17 stand-up:
- For now, when user uploads JSON, set flag to defer collision detection until user moves tissue block
- Also, keep UUID unchanged if tissue block is not moved or any other changes are being made
