### ISSUE TITLE
Update text in footer

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#877]
# Ready for dev
@katyb requests a quick text update to the footer:
- Remove `A state of the art visualization tool to envision large datasets developed by CNS, Indiana University.` and replace with: `A visualization tool for human organ experts to explore and compare Anatomical Structures, Cell Types, and Biomarkers (ASCT+B) Tables and OMAPs.`

![image](https://github.com/user-attachments/assets/cad52999-6fd3-487d-98fe-c1f96da7ae0e)

**Comment by emquardokus** [comment]
@LibbyUX issues fixed in PR https://github.com/hubmapconsortium/hra-ui/pull/882
