### ISSUE TITLE
8th release notes text/formatting tweaks

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#880]
# Ready for dev
Katy has requested tweaks for the 8th release notes page: https://humanatlas.io/release-notes/v2.2

### Data section
- Please update `71 3D Organ Models` to `71 3D Organ Models with 1,224 interior 3D anatomical structures`

![image](https://github.com/user-attachments/assets/3f4ec4ef-efa0-4ec8-8d00-15bd3077c32e)

### Publications section and Scholarly Publications subsection
- Please use italic formatting for all instances of `Nature Methods`
- Please remove `(27 additional authors not shown)`

Thank you so much!

![image](https://github.com/user-attachments/assets/b2713a8c-2fae-46e5-929b-b2d5c4f585fa)

**Comment by emquardokus** [comment]
Issues described in this issue were fixed in PR https://github.com/hubmapconsortium/hra-ui/pull/882
