### ISSUE TITLE
Update all instances of Dashboards to Dashboard

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#881]
# Ready for dev
Katy requests updates to all instances of `Dashboards` to `Dashboard` across all applications.

## https://apps.humanatlas.io/dashboard/
- Edit nav header to read `Dashboard`
  - See Figma for edit to [temporary header logo](https://www.figma.com/design/GAHPA5ni25Oq6qjeypvacx/Dashboards?node-id=3244-14337&t=LqIwFYGK5vEGqI0g-4) before we implement #812 
- Edit splash section body text to read:
`The Human Reference Atlas (HRA) is constructed and used by experts from many fields of science from around the globe. HRA Dashboard shows the size and coverage of HRA data; the number and type of HRA usage over time; publication and experimental data for the HRA; plus diversity of atlas authors, donors, and users.`

![image](https://github.com/user-attachments/assets/8f09b27c-dc5b-4eaa-ba52-b68aebfdf040)

### https://humanatlas.io/user-story/7
- Edit button to read `Dashboard`

![image](https://github.com/user-attachments/assets/45cf568d-a870-437b-9f2b-373e78d4c182)

### Global navigation
- Edit global navigation component to read `Dashboard`

![image](https://github.com/user-attachments/assets/3c3b5676-9828-417c-b92c-d7b2735193fd)

### https://humanatlas.io/release-notes/v2.2
- In the application section, please update to `Dashboard`

![image](https://github.com/user-attachments/assets/81006e6f-2b29-4828-90a1-f7864768532a)

**Comment by axdanbol** [comment]
@LibbyUX Please review: https://6762f006a214e2099955b681--hra-ui.netlify.app/

**Comment by LibbyUX** [comment]
@axdanbol - Approved, thank you so much!
